### ISSUE TITLE
Not receiving message after internet Re-connect

### ISSUE THREAD

**Issue by amitkumaroae** [QuickBlox/quickblox-android-sdk#120]
Hello,

All messages sent during disconnect lost.

Case: A & B are on Chat screen > B Switchoff I/N> A sends message to B > B Switch On I/N

I got the following logs when I turn the wifi off.

    java.net.SocketException: sendto failed: EPIPE (Broken pipe)
            at libcore.io.IoBridge.maybeThrowAfterSendto(IoBridge.java:546)
            at libcore.io.IoBridge.sendto(IoBridge.java:515)
            at java.net.PlainSocketImpl.write(PlainSocketImpl.java:504)
            at java.net.PlainSocketImpl.access$100(PlainSocketImpl.java:37)
            at java.net.PlainSocketImpl$PlainSocketOutputStream.write(PlainSocketImpl.java:266)
            at java.io.OutputStreamWriter.flushBytes(OutputStreamWriter.java:167)
            at java.io.OutputStreamWriter.flush(OutputStreamWriter.java:158)
            at java.io.BufferedWriter.flush(BufferedWriter.java:124)
            at org.jivesoftware.smack.util.ObservableWriter.flush(ObservableWriter.java:44)
            at org.jivesoftware.smack.tcp.PacketWriter.writePackets(PacketWriter.java:190)
            at org.jivesoftware.smack.tcp.PacketWriter.access$000(PacketWriter.java:40)
            at org.jivesoftware.smack.tcp.PacketWriter$1.run(PacketWriter.java:77)
     Caused by: android.system.ErrnoException: sendto failed: EPIPE (Broken pipe)
            at libcore.io.Posix.sendtoBytes(Native Method)
            at libcore.io.Posix.sendto(Posix.java:176)
            at libcore.io.BlockGuardOs.sendto(BlockGuardOs.java:278)
            at libcore.io.IoBridge.sendto(IoBridge.java:513)
            at java.net.PlainSocketImpl.write(PlainSocketImpl.java:504)
            at java.net.PlainSocketImpl.access$100(PlainSocketImpl.java:37)
            at java.net.PlainSocketImpl$PlainSocketOutputStream.write(PlainSocketImpl.java:266)
            at java.io.OutputStreamWriter.flushBytes(OutputStreamWriter.java:167)
            at java.io.OutputStreamWriter.flush(OutputStreamWriter.java:158)
            at java.io.BufferedWriter.flush(BufferedWriter.java:124)
            at org.jivesoftware.smack.util.ObservableWriter.flush(ObservableWriter.java:44)
            at org.jivesoftware.smack.tcp.PacketWriter.writePackets(PacketWriter.java:190)
            at org.jivesoftware.smack.tcp.PacketWriter.access$000(PacketWriter.java:40)
            at org.jivesoftware.smack.tcp.PacketWriter$1.run(PacketWriter.java:77)
11-04 17:16:15.572   7023-32251/com.entermixx W/XMPPConnection﹕ Connection closed with error
    java.net.SocketException: recvfrom failed: ETIMEDOUT (Connection timed out)
            at libcore.io.IoBridge.maybeThrowAfterRecvfrom(IoBridge.java:592)
            at libcore.io.IoBridge.recvfrom(IoBridge.java:556)
            at java.net.PlainSocketImpl.read(PlainSocketImpl.java:485)
            at java.net.PlainSocketImpl.access$000(PlainSocketImpl.java:37)
            at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:237)
            at java.io.InputStreamReader.read(InputStreamReader.java:231)
            at java.io.BufferedReader.read(BufferedReader.java:325)
            at org.jivesoftware.smack.util.ObservableReader.read(ObservableReader.java:38)
            at org.kxml2.io.KXmlParser.fillBuffer(KXmlParser.java:1515)
            at org.kxml2.io.KXmlParser.peekType(KXmlParser.java:992)
            at org.kxml2.io.KXmlParser.next(KXmlParser.java:349)
            at org.kxml2.io.KXmlParser.next(KXmlParser.java:313)
            at org.jivesoftware.smack.tcp.PacketReader.parsePackets(PacketReader.java:293)
            at org.jivesoftware.smack.tcp.PacketReader.access$000(PacketReader.java:49)
            at org.jivesoftware.smack.tcp.PacketReader$1.run(PacketReader.java:83)
     Caused by: android.system.ErrnoException: recvfrom failed: ETIMEDOUT (Connection timed out)
            at libcore.io.Posix.recvfromBytes(Native Method)
            at libcore.io.Posix.recvfrom(Posix.java:161)
            at libcore.io.BlockGuardOs.recvfrom(BlockGuardOs.java:250)
            at libcore.io.IoBridge.recvfrom(IoBridge.java:553)
            at java.net.PlainSocketImpl.read(PlainSocketImpl.java:485)
            at java.net.PlainSocketImpl.access$000(PlainSocketImpl.java:37)
            at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:237)
            at java.io.InputStreamReader.read(InputStreamReader.java:231)
            at java.io.BufferedReader.read(BufferedReader.java:325)
            at org.jivesoftware.smack.util.ObservableReader.read(ObservableReader.java:38)
            at org.kxml2.io.KXmlParser.fillBuffer(KXmlParser.java:1515)
            at org.kxml2.io.KXmlParser.peekType(KXmlParser.java:992)
            at org.kxml2.io.KXmlParser.next(KXmlParser.java:349)
            at org.kxml2.io.KXmlParser.next(KXmlParser.java:313)
            at org.jivesoftware.smack.tcp.PacketReader.parsePackets(PacketReader.java:293)
            at org.jivesoftware.smack.tcp.PacketReader.access$000(PacketReader.java:49)
            at org.jivesoftware.smack.tcp.PacketReader$1.run(PacketReader.java:83)

**Comment by katiatereshchenkova** [comment]
Hi! 
For getting the  "lost" messages, you need to add tracking of the Internet connection status in the application and when the Internet connection appears, you need to send a request to server to receive messages

**Comment by amitkumaroae** [comment]
Thanks for the answer.

I am already tracking  the Internet connection. When application re -connect the internet I login to chat again.

Now on re login to chat should deliver all undelivered messages as in case chat logout then chat login.

Here 1 more connected issue with this is :

As I am using automatic push notifications feature for the offline users.

USER B
Step 1 : internet disconnect during application in foreground mode.
Step 2: User minimize/kill the application.

USER A
Step 1: Send message to USER B.

USER B

Step 1: User should get push notification (FAILS)
Step 2: User should get message after maximize/relaunch the app (FAILS)

However I can get the all (lost) messages from the server (Using dialogs).

But my question is why push notification and message auto deliver fails in this particular condition??

**Comment by katiatereshchenkova** [comment]
We know about this issue. It will be fixed as soon as possible. 
But now you can try to request messages from the server in the activity in the method @Override protected void onResume ()

**Comment by vihangptl** [comment]
Hello,
I am also getting same issue.
will you find any solution?
