### ISSUE TITLE
Unable to make video call

### ISSUE THREAD

**Issue by abhishekSohagiya** [QuickBlox/quickblox-android-sdk#132]
I am able to use webrtc video call using your sample. But when I use my app id and user from our app to make audio or video call . I am getting following error.

  java.lang.ClassCastException: com.quickblox.chat.model.QBChatMessageExtension cannot be cast to org.jivesoftware.smack.packet.PacketExtension
 at com.quickblox.videochat.webrtc.RTCSignallingMessageProcessor.processSignalMessage(RTCSignallingMessageProcessor.java:69)
at com.quickblox.chat.QBWebRTCSignaling.deliver(QBWebRTCSignaling.java:88)
at com.quickblox.chat.QBVideoChatWebRTCSignalingManager.deliverMessage(QBVideoChatWebRTCSignalingManager.java:174)
                                                                                                 at com.quickblox.chat.QBVideoChatWebRTCSignalingManager.access$100(QBVideoChatWebRTCSignalingManager.java:22)
                                                                                                 at com.quickblox.chat.QBVideoChatWebRTCSignalingManager$1.processPacket(QBVideoChatWebRTCSignalingManager.java:57)
                                                                                                 at org.jivesoftware.smack.AbstractXMPPConnection$3.run(AbstractXMPPConnection.java:1105)
                                                                                                 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                                                 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                                                 at java.lang.Thread.run(Thread.java:818)

**Comment by soulfly** [comment]
which version of Android SDK do you use?

is it between Android-Android ?

**Comment by abhishekSohagiya** [comment]
yes , I am receiving new signaling added . But after that this error occurs. And new session is not being started. I faced this problem in Android-Android . While in Android to iOS , I can see call is coming but not able to receive.

**Comment by gstream** [comment]
I have same issue, too.

**Comment by pelipetsaa** [comment]
Is this issue still actual?
