### ISSUE TITLE
Unable to retrieve users list. 

### ISSUE THREAD

**Issue by Azhar0790** [QuickBlox/quickblox-android-sdk#138]
I have registered 15 entries but I am getting 0 entry... Please someone help me?

`final ListView opponentsList = (ListView) view.findViewById(R.id.opponentsList);

```
    QBRoster roster = QBChatService.getInstance().getRoster();
    ArrayList<Integer> userIds = new ArrayList<>(roster.getEntries().size());

    QBPagedRequestBuilder requestBuilder = new QBPagedRequestBuilder();
    requestBuilder.setPage(1);
    requestBuilder.setPerPage(userIds.size());
    for (QBRosterEntry user : roster.getEntries()) userIds.add(user.getUserId());
    if (roster.getEntries().size() == 0)


    QBUsers.getUsersByIDs(userIds, requestBuilder, new QBEntityCallbackImpl<ArrayList<QBUser>>() {
        @Override
        public void onSuccess(ArrayList<QBUser> results, Bundle params) {
            super.onSuccess(results, params);
            Log.e("OpponentsFragment", "Successfully loaded");
            Log.e("OpponentsFragment", "results :- "+results);
            Log.e("OpponentsFragment", "params :- "+params);
           ArrayList<QBUser> users = new ArrayList<>(results.size());
            Log.e("OpponentsFragment", "users:-"+users);
            for (QBUser result : results)
            {
                QBUser user = new QBUser();
                Log.e("OpponentsFragment", "user ....."+user);
                user.setId(result.getId());
                user.setLogin(result.getFullName());
                System.out.println(".............");
                System.out.println("Full name :- "+result.getFullName());
                users.add(user);
            }

            int i = searchIndexLogginedUser(users);
            if (i >= 0)
                users.remove(i);

            // Prepare users list for simple adapter.
            //
            opponentsAdapter = new OpponentsAdapter(getActivity(), users);
            opponentsList.setAdapter(opponentsAdapter);
        }

        @Override
        public void onError(List<String> errors) {
            Log.e("OpponentsFragment","Error on loading");
        }
    });`
```

**Comment by soulfly** [comment]
Please go to Admin panel, application settings and enable users retrieval logic.

https://www.evernote.com/l/ANgdG6JuP2FFv7MegP_xfzBLUTFX3-yZOIkB/image.png

This is disabled by security reason

**Comment by Azhar0790** [comment]
Thanks for the reply. But I have done the settings ..below is the logcat

`
02-05 14:23:29.811    8107-8107/com.quickblox.sample.videogroupchat D/OpponentsFragment﹕ onCreate() from OpponentsFragment
02-05 14:23:30.231    8107-8107/com.quickblox.sample.videogroupchat D/OpponentsFragment﹕ onCreate() from OpponentsFragment
02-05 14:23:31.322    8107-8107/com.quickblox.sample.videogroupchat E/OpponentsFragment﹕ Successfully loaded
02-05 14:23:31.322    8107-8107/com.quickblox.sample.videogroupchat E/OpponentsFragment﹕ results :- []
02-05 14:23:31.322    8107-8107/com.quickblox.sample.videogroupchat E/OpponentsFragment﹕ params :- Bundle[{total_pages=0, per_page=1, total_entries=0, current_page=1}]
02-05 14:23:31.322    8107-8107/com.quickblox.sample.videogroupchat E/OpponentsFragment﹕ users:-[]
02-05 14:23:31.322    8107-8107/com.quickblox.sample.videogroupchat E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.quickblox.sample.videogroupchat, PID: 8107
    java.lang.NullPointerException
            at android.view.LayoutInflater.from(LayoutInflater.java:211)
            at com.quickblox.sample.groupchatwebrtc.adapters.OpponentsAdapter.<init>(OpponentsAdapter.java:32)
            at com.quickblox.sample.groupchatwebrtc.fragments.OpponentsFragment$2.onSuccess(OpponentsFragment.java:119)
            at com.quickblox.sample.groupchatwebrtc.fragments.OpponentsFragment$2.onSuccess(OpponentsFragment.java:93)
            at com.quickblox.core.query.Query.notifySuccess(Query.java:314)
            at com.quickblox.core.query.Query$VersionEntityCallback.completedWithResponse(Query.java:346)
            at com.quickblox.core.query.Query.completedWithResponse(Query.java:260)
            at com.quickblox.core.server.HttpRequestRunnable$1.handleMessage(HttpRequestRunnable.java:41)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5372)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:970)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:786)
            at dalvik.system.NativeStart.main(Native Method)
`

**Comment by soulfly** [comment]
I don't see anything in it, please reformat

**Comment by Azhar0790** [comment]
Please see it again.

02-05 14:23:29.811    8107-8107/com.quickblox.sample.videogroupchat D/OpponentsFragment﹕ onCreate() from OpponentsFragment
02-05 14:23:30.231    8107-8107/com.quickblox.sample.videogroupchat D/OpponentsFragment﹕ onCreate() from OpponentsFragment
02-05 14:23:31.322    8107-8107/com.quickblox.sample.videogroupchat E/OpponentsFragment﹕ Successfully loaded
02-05 14:23:31.322    8107-8107/com.quickblox.sample.videogroupchat E/OpponentsFragment﹕ results :- []
02-05 14:23:31.322    8107-8107/com.quickblox.sample.videogroupchat E/OpponentsFragment﹕ params :- Bundle[{total_pages=0, per_page=1, total_entries=0, current_page=1}]
02-05 14:23:31.322    8107-8107/com.quickblox.sample.videogroupchat E/OpponentsFragment﹕ users:-[]
02-05 14:23:31.322    8107-8107/com.quickblox.sample.videogroupchat E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.quickblox.sample.videogroupchat, PID: 8107
    java.lang.NullPointerException
            at android.view.LayoutInflater.from(LayoutInflater.java:211)
            at com.quickblox.sample.groupchatwebrtc.adapters.OpponentsAdapter.<init>(OpponentsAdapter.java:32)
            at com.quickblox.sample.groupchatwebrtc.fragments.OpponentsFragment$2.onSuccess(OpponentsFragment.java:119)
            at com.quickblox.sample.groupchatwebrtc.fragments.OpponentsFragment$2.onSuccess(OpponentsFragment.java:93)
            at com.quickblox.core.query.Query.notifySuccess(Query.java:314)
            at com.quickblox.core.query.Query$VersionEntityCallback.completedWithResponse(Query.java:346)
            at com.quickblox.core.query.Query.completedWithResponse(Query.java:260)
            at com.quickblox.core.server.HttpRequestRunnable$1.handleMessage(HttpRequestRunnable.java:41)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5372)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:970)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:786)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by Azhar0790** [comment]
Sir any idea what should I do here now?

**Comment by soulfly** [comment]
Can you debug and check what is the cause of java.lang.NullPointerException

**Comment by pelipetsaa** [comment]
Is this issue still actual?
