### ISSUE TITLE
App crashes on Nexus 6 

### ISSUE THREAD

**Issue by jackyph** [QuickBlox/quickblox-android-sdk#140]
We are evaluating your SDK and tried running it on a Nexus 6 (Android 6.0), but it keeps crashing when we press "Video Call". 

```

02-11 14:53:21.097 29977-29977/com.quickblox.sample.groupchatwebrtc E/SettingsUtil: resolutionItem =: -1
02-11 14:53:21.098 29977-29977/com.quickblox.sample.groupchatwebrtc E/SettingsUtil: videoCodecItem =: VP8
02-11 14:53:21.098 29977-29977/com.quickblox.sample.groupchatwebrtc E/SettingsUtil: audioCodec =: ISAC
02-11 14:53:21.161 29977-29977/com.quickblox.sample.groupchatwebrtc E/RecyclerView: No adapter attached; skipping layout
02-11 14:53:21.240 29977-30869/com.quickblox.sample.groupchatwebrtc E/WebRtcAudioManager: Nexus 6 is blacklisted for OpenSL ES usage!
02-11 14:53:21.558 29977-30862/com.quickblox.sample.groupchatwebrtc E/VideoCapturerAndroid: Open camera failed on id 1
                                                                                            java.lang.RuntimeException: Fail to connect to camera service
                                                                                                at android.hardware.Camera.<init>(Camera.java:495)
                                                                                                at android.hardware.Camera.open(Camera.java:341)
                                                                                                at org.webrtc.VideoCapturerAndroid.getSupportedFormats(VideoCapturerAndroid.java:406)
                                                                                                at org.webrtc.VideoCapturerAndroid.initStatics(VideoCapturerAndroid.java:314)
                                                                                                at org.webrtc.VideoCapturerAndroid.init(VideoCapturerAndroid.java:285)
                                                                                                at org.webrtc.VideoCapturer.nativeCreateVideoCapturer(Native Method)
                                                                                                at org.webrtc.VideoCapturer.create(VideoCapturer.java:38)
                                                                                                at org.webrtc.VideoCapturerAndroid.create(VideoCapturerAndroid.java:219)
                                                                                                at com.quickblox.videochat.webrtc.QBMediaStreamManager.initVideoTrack(QBMediaStreamManager.java:135)
                                                                                                at com.quickblox.videochat.webrtc.QBMediaStreamManager.initLocalMediaStream(QBMediaStreamManager.java:100)
                                                                                                at com.quickblox.videochat.webrtc.QBRTCSession.onLocalStreamNeedAdd(QBRTCSession.java:1112)
                                                                                                at com.quickblox.videochat.webrtc.QBPeerChannel.setLocalMediaStream(QBPeerChannel.java:143)
                                                                                                at com.quickblox.videochat.webrtc.QBPeerChannel.access$700(QBPeerChannel.java:41)
                                                                                                at com.quickblox.videochat.webrtc.QBPeerChannel$1.run(QBPeerChannel.java:133)
                                                                                                at android.os.Handler.handleCallback(Handler.java:739)
                                                                                                at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                                at android.os.Looper.loop(Looper.java:148)
                                                                                                at com.quickblox.videochat.webrtc.LooperExecutor.run(LooperExecutor.java:73)
02-11 14:53:21.559 29977-30862/com.quickblox.sample.groupchatwebrtc E/VideoCapturerAndroid: Fail to get supported formats for camera 1
02-11 14:53:21.562 29977-30862/com.quickblox.sample.groupchatwebrtc E/VideoCapturerAndroid: Open camera failed on id 1
                                                                                            java.lang.RuntimeException: Fail to connect to camera service
                                                                                                at android.hardware.Camera.<init>(Camera.java:495)
                                                                                                at android.hardware.Camera.open(Camera.java:341)
                                                                                                at org.webrtc.VideoCapturerAndroid.getSupportedFormats(VideoCapturerAndroid.java:406)
                                                                                                at org.webrtc.VideoCapturerAndroid.initStatics(VideoCapturerAndroid.java:314)
                                                                                                at org.webrtc.VideoCapturerAndroid.init(VideoCapturerAndroid.java:285)
                                                                                                at org.webrtc.VideoCapturer.nativeCreateVideoCapturer(Native Method)
                                                                                                at org.webrtc.VideoCapturer.create(VideoCapturer.java:38)
                                                                                                at org.webrtc.VideoCapturerAndroid.create(VideoCapturerAndroid.java:219)
                                                                                                at com.quickblox.videochat.webrtc.QBMediaStreamManager.initVideoTrack(QBMediaStreamManager.java:138)
                                                                                                at com.quickblox.videochat.webrtc.QBMediaStreamManager.initLocalMediaStream(QBMediaStreamManager.java:100)
                                                                                                at com.quickblox.videochat.webrtc.QBRTCSession.onLocalStreamNeedAdd(QBRTCSession.java:1112)
                                                                                                at com.quickblox.videochat.webrtc.QBPeerChannel.setLocalMediaStream(QBPeerChannel.java:143)
                                                                                                at com.quickblox.videochat.webrtc.QBPeerChannel.access$700(QBPeerChannel.java:41)
                                                                                                at com.quickblox.videochat.webrtc.QBPeerChannel$1.run(QBPeerChannel.java:133)
                                                                                                at android.os.Handler.handleCallback(Handler.java:739)
                                                                                                at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                                at android.os.Looper.loop(Looper.java:148)
                                                                                                at com.quickblox.videochat.webrtc.LooperExecutor.run(LooperExecutor.java:73)
02-11 14:53:21.562 29977-30862/com.quickblox.sample.groupchatwebrtc E/VideoCapturerAndroid: Fail to get supported formats for camera 1
02-11 14:53:21.670 29977-30862/com.quickblox.sample.groupchatwebrtc E/AndroidRuntime: FATAL EXCEPTION: Thread-1084
                                                                                      Process: com.quickblox.sample.groupchatwebrtc, PID: 29977
                                                                                      java.lang.NullPointerException: Attempt to invoke virtual method 'long org.webrtc.VideoCapturer.takeNativeVideoCapturer()' on a null object reference
                                                                                          at org.webrtc.PeerConnectionFactory.createVideoSource(PeerConnectionFactory.java:111)
                                                                                          at com.quickblox.videochat.webrtc.QBMediaStreamManager.createVideoTrack(QBMediaStreamManager.java:158)
                                                                                          at com.quickblox.videochat.webrtc.QBMediaStreamManager.initVideoTrack(QBMediaStreamManager.java:143)
                                                                                          at com.quickblox.videochat.webrtc.QBMediaStreamManager.initLocalMediaStream(QBMediaStreamManager.java:100)
                                                                                          at com.quickblox.videochat.webrtc.QBRTCSession.onLocalStreamNeedAdd(QBRTCSession.java:1112)
                                                                                          at com.quickblox.videochat.webrtc.QBPeerChannel.setLocalMediaStream(QBPeerChannel.java:143)
                                                                                          at com.quickblox.videochat.webrtc.QBPeerChannel.access$700(QBPeerChannel.java:41)
                                                                                          at com.quickblox.videochat.webrtc.QBPeerChannel$1.run(QBPeerChannel.java:133)
                                                                                          at android.os.Handler.handleCallback(Handler.java:739)
                                                                                          at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                          at android.os.Looper.loop(Looper.java:148)
                                                                                          at com.quickblox.videochat.webrtc.LooperExecutor.run(LooperExecutor.java:73)

```

**Comment by ingerul93** [comment]
Please check camera permission in Settings and try again. :)

**Comment by gstream** [comment]
I have same issues.

**Comment by arpit87** [comment]
I am facing same problem. I think the problem is with Android 6 and not related to device

**Comment by pelipetsaa** [comment]
Is this issue still actual?

**Comment by hareshsandeep** [comment]
I had same issue and it stopped crashing once I had Camera Permission.

**Comment by ozanurkn** [comment]
guys  i have still same issue , what can i do for solution?anybody can help me ?

**Comment by tatanka987** [comment]
@ozanurkn did you reproduce it on our sample without any changes?

**Comment by lisitso** [comment]
same issue here, even if all permissions was granted. Any suggestion?
