### ISSUE TITLE
Null Pointer Exception During video conference

### ISSUE THREAD

**Issue by ingerul93** [QuickBlox/quickblox-android-sdk#150]
Hi. I tried to make a video conference(QB SDK 2.5). After selecting users and press VIDEO CALL Button, this happens:

03-10 15:13:18.217 21552-21552/com.quickblox.sample.groupchatwebrtc E/RecyclerView: No adapter attached; skipping layout
03-10 15:13:27.054 21552-24263/com.quickblox.sample.groupchatwebrtc E/AndroidRuntime: FATAL EXCEPTION: Thread-1586
                                                                                      Process: com.quickblox.sample.groupchatwebrtc, PID: 21552
                                                                                      java.lang.NullPointerException: Attempt to invoke virtual method 'void org.webrtc.PeerConnection.setRemoteDescription(org.webrtc.SdpObserver, org.webrtc.SessionDescription)' on a null object reference
                                                                                          at com.quickblox.videochat.webrtc.QBPeerChannel$6.run(QBPeerChannel.java:245)
                                                                                          at android.os.Handler.handleCallback(Handler.java:739)
                                                                                          at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                          at android.os.Looper.loop(Looper.java:148)
                                                                                          at com.quickblox.videochat.webrtc.LooperExecutor.run(LooperExecutor.java:73)

**Comment by gstream** [comment]
What is your android device model?
I have same issue with you.

**Comment by ingerul93** [comment]
LG Nexus 5, Android-Android. This happens all time.

**Comment by gstream** [comment]
What is your android version ?
I have same issue only on android 6.

**Comment by ingerul93** [comment]
Android 6.0.1(Pure Nexus ROM). This happens too on Android 6.0.1 Stock ROM

**Comment by gstream** [comment]
Did you test your app on the other device model ? (Samsung, HTC, GSmart, THL, etc)

**Comment by ingerul93** [comment]
I dont have other devices now.

**Comment by gstream** [comment]
This is quickblox issue.
I have same issue on Nexus 5.
So I posted this issue .
[https://github.com/QuickBlox/quickblox-android-sdk/issues/146]
Quickblox said that they are going to fix this issue and will release next version.

**Comment by ingerul93** [comment]
Ok. Now on my S3 i see this after Video call is closed/hangup...:


03-10 17:30:37.360 14761-17055/com.quickblox.sample.groupchatwebrtc E/AndroidRuntime: FATAL EXCEPTION: Thread-1293
                                                                                      java.lang.NullPointerException
                                                                                          at com.quickblox.videochat.webrtc.QBPeerChannel$8.run(QBPeerChannel.java:394)
                                                                                          at android.os.Handler.handleCallback(Handler.java:730)
                                                                                          at android.os.Handler.dispatchMessage(Handler.java:92)
                                                                                          at android.os.Looper.loop(Looper.java:176)
                                                                                          at com.quickblox.videochat.webrtc.LooperExecutor.run(LooperExecutor.java:73)

wtf o.O

**Comment by gstream** [comment]
Current version of QB SDK is very unstable.
So what do you think of this issue ?
Is it related with QB SDK ? or depends on android version ?

**Comment by ingerul93** [comment]
I see. I dont know. Maybe its related to QB SDK and not related with android version. Older QB SDK(2.3) works perfect on my Nexus 5.

**Comment by gstream** [comment]
Current version of QB SDK works perfect on android 4+, 5+ (Nexus 5).

**Comment by Ygauraw** [comment]
It doesn't work for my Samsung Music Duos (JellyBean) or Infocus (Lolipop) either.

**Comment by tatanka987** [comment]
Use latest version of QuickBlox Android SDK https://quickblox.com/developers/Android
Closed for long inactivity.
