### ISSUE TITLE
automatically finish call in few seconds with below error. I implement  QuickBlox API in Service

### ISSUE THREAD

**Issue by yevhenho** [QuickBlox/quickblox-android-sdk#168]
java.lang.IllegalStateException: Is not active session
            at com.quickblox.videochat.webrtc.QBRTCSession.onChannelConnectionConnecting(QBRTCSession.java:1105)
            at com.quickblox.videochat.webrtc.QBPeerChannel$PCObserver$1.run(QBPeerChannel.java:538)
            at android.os.Handler.handleCallback(Handler.java:800)
            at android.os.Handler.dispatchMessage(Handler.java:100)
            at android.os.Looper.loop(Looper.java:194)
            at com.quickblox.videochat.webrtc.LooperExecutor.run(LooperExecutor.java:73)

**Comment by vfite** [comment]
Hi. We've already fixed this issue. New sdk version will be released in a few days. Check new version on our site : http://quickblox.com/developers/Android

**Comment by yevhenho** [comment]
thank u, this problem has  fixed
