### ISSUE TITLE
java.lang.IllegalStateException: Chat is not initialized

### ISSUE THREAD

**Issue by harshadaasai** [QuickBlox/quickblox-android-sdk#171]
QBGroupChatManager groupChatManager = QBChatService.getInstance().getGroupChatManager();

Here in above code i am getting an error as: 

04-18 08:45:48.396 27658-27658/com.aperotechnologies.eventapplication E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                        java.lang.IllegalStateException: Chat is not initialized
                                                                                            at com.quickblox.chat.QBChatService.getInstance(QBChatService.java:159)
                                                                                            at com.aperotechnologies.eventapplication.AcceptReqforParty.createGroupChat(AcceptReqforParty.java:151)
                                                                                            at com.aperotechnologies.eventapplication.AcceptReqforParty.access$100(AcceptReqforParty.java:35)
                                                                                            at com.aperotechnologies.eventapplication.AcceptReqforParty$1.onSuccess(AcceptReqforParty.java:112)
                                                                                            at com.aperotechnologies.eventapplication.AcceptReqforParty$1.onSuccess(AcceptReqforParty.java:97)
                                                                                            at com.quickblox.core.query.Query.notifySuccess(Query.java:304)
                                                                                            at com.quickblox.core.query.Query$VersionEntityCallback.completedWithResponse(Query.java:336)
                                                                                            at com.quickblox.core.query.Query.completedWithResponse(Query.java:250)
                                                                                            at com.quickblox.core.server.HttpRequestRunnable$1.handleMessage(HttpRequestRunnable.java:43)
                                                                                            at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                            at android.os.Looper.loop(Looper.java:137)
                                                                                            at android.app.ActivityThread.main(ActivityThread.java:4745)
                                                                                            at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                            at java.lang.reflect.Method.invoke(Method.java:511)
                                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
                                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
                                                                                            at dalvik.system.NativeStart.main(Native Method)

**Comment by soulfly** [comment]
Which SDK version do you use?
