### ISSUE TITLE
Keeps crashing when I try to start a Video Call

### ISSUE THREAD

**Issue by Ygauraw** [QuickBlox/quickblox-android-sdk#192]
E/VideoCapturerAndroid: Open camera failed on id 1
java.lang.RuntimeException: Fail to connect to camera service
at android.hardware.Camera.<init>(Camera.java:637)                                                                                   at android.hardware.Camera.open(Camera.java:474)                                                                                   at org.webrtc.VideoCapturerAndroid.getSupportedFormats(VideoCapturerAndroid.java:406)at org.webrtc.VideoCapturerAndroid.initStatics(VideoCapturerAndroid.java:314)                                                                                   at org.webrtc.VideoCapturerAndroid.init(VideoCapturerAndroid.java:285)                                                                                   at org.webrtc.VideoCapturer.nativeCreateVideoCapturer(Native Method)                                                                                   at org.webrtc.VideoCapturer.create(VideoCapturer.java:38)                                                                                   at org.webrtc.VideoCapturerAndroid.create(VideoCapturerAndroid.java:219)                                                                                   at com.quickblox.videochat.webrtc.QBMediaStreamManager.initVideoTrack(QBMediaStreamManager.java:137)
at com.quickblox.videochat.webrtc.QBMediaStreamManager.initLocalMediaStream(QBMediaStreamManager.java:99)  
at com.quickblox.videochat.webrtc.QBRTCSession.onLocalStreamNeedAdd(QBRTCSession.java:1113)                                                                                   at com.quickblox.videochat.webrtc.QBPeerChannel.setLocalMediaStream(QBPeerChannel.java:146)                                                                                   at com.quickblox.videochat.webrtc.QBPeerChannel.access$700(QBPeerChannel.java:41)                                                                                   at com.quickblox.videochat.webrtc.QBPeerChannel$1.run(QBPeerChannel.java:133)                                                                                   at android.os.Handler.handleCallback(Handler.java:810)                                                                                   at android.os.Handler.dispatchMessage(Handler.java:99)                                                                                   at android.os.Looper.loop(Looper.java:189)
at com.quickblox.videochat.webrtc.LooperExecutor.run(LooperExecutor.java:73)

W/System.err: java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0
E/VideoCapturerAndroid: Fail to get supported formats for camera 1
W/System.err:     at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
W/System.err:     at java.util.ArrayList.get(ArrayList.java:308)
W/System.err:     at org.webrtc.VideoCapturerAndroid.getSupportedFormatsAsJson(VideoCapturerAndroid.java:385)
W/System.err:     at org.webrtc.VideoCapturerAndroid.getSupportedFormatsAsJson(VideoCapturerAndroid.java:334)
W/System.err:     at org.webrtc.VideoCapturer.nativeCreateVideoCapturer(Native Method)
W/System.err:     at org.webrtc.VideoCapturer.create(VideoCapturer.java:38)
W/System.err:     at org.webrtc.VideoCapturerAndroid.create(VideoCapturerAndroid.java:219)
W/System.err:     at com.quickblox.videochat.webrtc.QBMediaStreamManager.initVideoTrack(QBMediaStreamManager.java:137)
W/System.err:     at com.quickblox.videochat.webrtc.QBMediaStreamManager.initLocalMediaStream(QBMediaStreamManager.java:99)
W/System.err:     at com.quickblox.videochat.webrtc.QBRTCSession.onLocalStreamNeedAdd(QBRTCSession.java:1113)
W/System.err:     at com.quickblox.videochat.webrtc.QBPeerChannel.setLocalMediaStream(QBPeerChannel.java:146)
W/System.err:     at com.quickblox.videochat.webrtc.QBPeerChannel.access$700(QBPeerChannel.java:41)
W/System.err:     at com.quickblox.videochat.webrtc.QBPeerChannel$1.run(QBPeerChannel.java:133)
W/System.err:     at android.os.Handler.handleCallback(Handler.java:810)
W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:99)
W/System.err:     at android.os.Looper.loop(Looper.java:189)
W/System.err:     at com.quickblox.videochat.webrtc.LooperExecutor.run(LooperExecutor.java:73)E/rtc:       #
          # Fatal error in ../../talk/app/webrtc/java/jni/androidvideocapturer_jni.cc, line 164
          # Check failed: !jni()->ExceptionCheck()
          # error during supportedFormatsAsJson
          #

E/VideoCapturerAndroid: InitStatics failed
java.lang.NullPointerException: Attempt to invoke interface method 'boolean java.util.List.add(java.lang.Object)' on a null object reference
at org.webrtc.VideoCapturerAndroid.initStatics(VideoCapturerAndroid.java:320)
at org.webrtc.VideoCapturerAndroid.init(VideoCapturerAndroid.java:285)
at org.webrtc.VideoCapturer.nativeCreateVideoCapturer(Native Method)
at org.webrtc.VideoCapturer.create(VideoCapturer.java:38)
at org.webrtc.VideoCapturerAndroid.create(VideoCapturerAndroid.java:219)
at com.quickblox.videochat.webrtc.QBMediaStreamManager.initVideoTrack(QBMediaStreamManager.java:134)
at com.quickblox.videochat.webrtc.QBMediaStreamManager.initLocalMediaStream(QBMediaStreamManager.java:99)
at com.quickblox.videochat.webrtc.QBRTCSession.onLocalStreamNeedAdd(QBRTCSession.java:1113)
at com.quickblox.videochat.webrtc.QBPeerChannel.setLocalMediaStream(QBPeerChannel.java:146)
at com.quickblox.videochat.webrtc.QBPeerChannel.access$700(QBPeerChannel.java:41)
at com.quickblox.videochat.webrtc.QBPeerChannel$1.run(QBPeerChannel.java:133)
at android.os.Handler.handleCallback(Handler.java:810)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:189)
at com.quickblox.videochat.webrtc.LooperExecutor.run(LooperExecutor.java:73)`

 W/google-breakpad: ### ### ### ### ### ### ### ### ### ### ### ### ###
W/google-breakpad: Chrome build fingerprint:
W/google-breakpad: 0.1
W/google-breakpad: 8
W/google-breakpad: 3287cb47-323f-452a-9071-08e954855982
google-breakpad: ### ### ### ### ### ### ### ### ### ### ### ### ###
A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 7057 (Thread-3758)

**Comment by tatanka987** [comment]
which version QuickBlox Android SDK do you use?

**Comment by Ygauraw** [comment]
I am using 2.4

**Comment by RomanPronin** [comment]
Here is latest version [SDK](https://quickblox.com/developers/Android) and [video-chat-sample](https://github.com/QuickBlox/quickblox-android-sdk/tree/master/sample-videochat-webrtc).

**Comment by vfite** [comment]
Closed for long inactivity
