### ISSUE TITLE
Crash when receive the call 

### ISSUE THREAD

**Issue by sonnguyen0310** [QuickBlox/quickblox-android-sdk#193]
Hi, when client had signal call incoming, i got crash with the log cat

E/AndroidRuntime: FATAL EXCEPTION: Thread-10080
                                                               PID: 14954
                                                                java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference
                                                                    at com.quickblox.videochat.webrtc.QBRTCSession.initSignallingWithOpponents(QBRTCSession.java:882)
                                                                    at com.quickblox.videochat.webrtc.QBRTCSession.<init>(QBRTCSession.java:139)
                                                                    at com.quickblox.videochat.webrtc.QBRTCClient.createSessionWithDescription(QBRTCClient.java:188)
                                                                    at com.quickblox.videochat.webrtc.QBRTCClient.getOrCreateSession(QBRTCClient.java:403)
                                                                    at com.quickblox.videochat.webrtc.QBRTCClient.access$000(QBRTCClient.java:53)
                                                                    at com.quickblox.videochat.webrtc.QBRTCClient$1.run(QBRTCClient.java:390)
                                                                    at android.os.Handler.handleCallback(Handler.java:739)
                                                                    at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                    at android.os.Looper.loop(Looper.java:145)
                                                                    at com.quickblox.videochat.webrtc.LooperExecutor.run(LooperExecutor.java:73)

Please help me

**Comment by shireen028** [comment]
Any luck with this issue?

**Comment by sonnguyen0310** [comment]
update to 2.6 and it work well
