### ISSUE TITLE
Parcelable encountered IOException writing serializable object (name = com.quickblox.chat.model.QBDialog)

### ISSUE THREAD

**Issue by mediendev** [QuickBlox/quickblox-android-sdk#222]
When I pass Custom Data to  Dialogs, I keep getting the above error....when I try to join the ChatRoom. The Dialogs work fine without custom Data. 

  java.lang.RuntimeException: Parcelable encountered IOException writing serializable object (name = com.quickblox.chat.model.QBDialog)
            at android.os.Parcel.writeSerializable(Parcel.java:1388)
            at android.os.Parcel.writeValue(Parcel.java:1335)
            at android.os.Parcel.writeArrayMapInternal(Parcel.java:638)
            at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1313)
            at android.os.Bundle.writeToParcel(Bundle.java:1096)
            at android.os.Parcel.writeBundle(Parcel.java:663)
            at android.content.Intent.writeToParcel(Intent.java:7192)
  Caused by: java.io.NotSerializableException: org.json.JSONObject$1

 public static void startForResult(Activity activity, int code, QBDialog dialog) {
        Intent intent = new Intent(activity, ChatActivity.class);  
        ***_intent.putExtra(ChatActivity.EXTRA_DIALOG,dialog);**_*
        activity.startActivityForResult(intent, code);
    }

Anyone encountered this error? Could anyone suggest solution please

**Comment by niihelium** [comment]
@mediendev the only thing I've found about it is here: http://stackoverflow.com/questions/36834145/parcelable-encountered-ioexception-writing-serializable-object-quickblox-dialog

Looks like it's real bug.

**Comment by jatin-lakhani** [comment]
+1
Having same issue...
Any one has solution then please post

Thanks

**Comment by Hafiz-Waleed-Hussain** [comment]
+1
Same issue. Bad

**Comment by tatanka987** [comment]
hello, for correct deserialization QBdialog's custom data, this custom data not must to contain unserializable fields or you can create a custom model like [ParselableQBDialog](https://github.com/QuickBlox/q-municate-android/blob/master/Q-municate_core/src/main/java/com/quickblox/q_municate_core/models/ParcelableQBDialog.java) for getting serializable functions. You can use new model like [there ](https://github.com/QuickBlox/q-municate-android/blob/master/Q-municate_core/src/main/java/com/quickblox/q_municate_core/qb/commands/chat/QBLoadDialogsCommand.java#L68)

**Comment by tatanka987** [comment]
Close. Long time inactivity.

**Comment by rohitsharma181589** [comment]
I am still facing this issue, Any help.
Caused by: java.io.NotSerializableException: org.json.JSONObject$1
        at java.io.ObjectOutputStream.writeNewObject(ObjectOutputStream.java:1344)
        at java.io.ObjectOutputStream.writeObjectInternal(ObjectOutputStream.java:1651)
        at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1497)
        at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1461)
        at java.util.HashMap.writeObject(HashMap.java:976)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.io.ObjectOutputStream.writeHierarchy(ObjectOutputStream.java:1033)
        at java.io.ObjectOutputStream.writeNewObject(ObjectOutputStream.java:1384)
        at java.io.ObjectOutputStream.writeObjectInternal(ObjectOutputStream.java:1651)
        at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1497)
        at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1461)
        at java.io.ObjectOutputStream.writeFieldValues(ObjectOutputStream.java:959)
        at java.io.ObjectOutputStream.defaultWriteObject(ObjectOutputStream.java:360)
        at java.io.ObjectOutputStream.writeHierarchy(ObjectOutputStream.java:1054)
        at java.io.ObjectOutputStream.writeNewObject(ObjectOutputStream.java:1384)
        at java.io.ObjectOutputStream.writeObjectInternal(ObjectOutputStream.java:1651)
        at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1497)
        at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1461)
    	at java.io.ObjectOutputStream.writeFieldValues(Objec
