### ISSUE TITLE
Client disconnect continously

### ISSUE THREAD

**Issue by Hemant0601** [QuickBlox/quickblox-android-sdk#235]
First of all I want to ask , is there a portal where you guys solve issues and at least acknowledge, because the day I have started using and even after getting a PRO account I have no luck solving my issues from your side. Whether its on GITHUB, STACKOVERFLOW or the ticket system on your homepage website.

Anyways, trying my luck again,  so recently I am getting an issue where the QB service gets disconnected whenever I try to send message or presence. then it reconnects and then same.

Below is my log, Please look into it.
And this is happening again and again, it disconnects then connect again and as soon as i try to "send message", "send presence" it drops again. Please help

ASDK: QBPrivateChatManager, sending a message with id 5772721e154f83a10d4b31c4
07-02 10:53:16.801 17715-17715/com.softdew.orahi E/PrivateChatConnCentral: Client is not, or no longer, connected.
07-02 10:53:16.845 17715-17715/com.softdew.orahi I/OrahiBaseActivity: OnStart
07-02 10:53:16.855 17715-31163/com.softdew.orahi W/System.err: org.jivesoftware.smack.SmackException$NotConnectedException: Client is not, or no longer, connected.
07-02 10:53:16.869 17715-31163/com.softdew.orahi W/System.err:     at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketWriter.throwNotConnectedExceptionIfDoneAndResumptionNotPossible(XMPPTCPConnection.java:1244)
07-02 10:53:16.870 17715-31163/com.softdew.orahi W/System.err:     at org.jivesoftware.smack.tcp.XMPPTCPConnection.throwNotConnectedExceptionIfAppropriate(XMPPTCPConnection.java:345)
07-02 10:53:16.870 17715-31163/com.softdew.orahi W/System.err:     at org.jivesoftware.smack.AbstractXMPPConnection.sendStanza(AbstractXMPPConnection.java:617)
07-02 10:53:16.870 17715-31163/com.softdew.orahi W/System.err:     at com.quickblox.chat.QBMessageStatusesSender.sendReadStatus(QBMessageStatusesSender.java:24)
07-02 10:53:16.871 17715-31163/com.softdew.orahi W/System.err:     at com.quickblox.chat.QBMessageStatusesSender.sendReadStatus(QBMessageStatusesSender.java:19)
07-02 10:53:16.872 17715-31163/com.softdew.orahi W/System.err:     at com.quickblox.chat.QBPrivateChatManager.sendReadStatus(QBPrivateChatManager.java:154)
07-02 10:53:16.872 17715-31163/com.softdew.orahi W/System.err:     at com.quickblox.chat.QBPrivateChat.readMessage(QBPrivateChat.java:145)
07-02 10:53:16.873 17715-31163/com.softdew.orahi W/System.err:     at com.softdew.orahi.chat.ui.activities.ChatActivity$17.run(ChatActivity.java:1173)
07-02 10:53:16.873 17715-31163/com.softdew.orahi W/System.err:     at android.os.Handler.handleCallback(Handler.java:733)
07-02 10:53:16.874 17715-31163/com.softdew.orahi W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
07-02 10:53:16.876 17715-31163/com.softdew.orahi W/System.err:     at android.os.Looper.loop(Looper.java:136)
07-02 10:53:16.877 17715-31163/com.softdew.orahi W/System.err:     at android.os.HandlerThread.run(HandlerThread.java:61)
07-02 10:53:17.461 17715-17715/com.softdew.orahi V/ChatService: getting chat dialogs from QB .... 
07-02 10:53:17.472 17715-31181/com.softdew.orahi D/QBASDK: =========================================================
                                                           === REQUEST ==== 32668976-85c8-4e8b-84a6-ba5579d055c5 ===
                                                           REQUEST
                                                               GET https://api.quickblox.com/chat/Dialog.json
                                                           HEADERS
                                                               QuickBlox-REST-API-Version=0.1.1
                                                               QB-SDK=Android 2.6
                                                               QB-Token=9a9910b9dd7cea1104adf4061d2bf6b5d399efad
                                                           PARAMETERS
                                                               limit=30
                                                           INLINE
                                                               GET https://api.quickblox.com/chat/Dialog.json?limit=30
07-02 10:53:17.694 17715-17715/com.softdew.orahi I/OrahiBaseActivity: OnStop
07-02 10:53:21.770 17715-21701/com.softdew.orahi W/XMPPTCPConnection: shutdownDone was not marked as successful by the writer thread
                                                                      org.jivesoftware.smack.SmackException$NoResponseException: No response received within reply timeout. Timeout was 5000ms (~5s). Used filter: No filter used or filter was 'null'.
                                                                          at org.jivesoftware.smack.SynchronizationPoint.checkForResponse(SynchronizationPoint.java:253)
                                                                          at org.jivesoftware.smack.SynchronizationPoint.checkIfSuccessOrWait(SynchronizationPoint.java:146)
                                                                          at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketWriter.shutdown(XMPPTCPConnection.java:1283)
                                                                          at org.jivesoftware.smack.tcp.XMPPTCPConnection.shutdown(XMPPTCPConnection.java:507)
                                                                          at org.jivesoftware.smack.tcp.XMPPTCPConnection.instantShutdown(XMPPTCPConnection.java:496)
                                                                          at org.jivesoftware.smack.tcp.XMPPTCPConnection.notifyConnectionError(XMPPTCPConnection.java:876)
                                                                          at org.jivesoftware.smack.tcp.XMPPTCPConnection.access$2800(XMPPTCPConnection.java:140)
                                                                          at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketWriter.writePackets(XMPPTCPConnection.java:1433)
                                                                          at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketWriter.access$2900(XMPPTCPConnection.java:1184)
                                                                          at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketWriter$1.run(XMPPTCPConnection.java:1232)
                                                                          at java.lang.Thread.run(Thread.java:841)
07-02 10:53:21.772 17715-21701/com.softdew.orahi W/AbstractXMPPConnection: Connection closed with error
                                                                           java.lang.NullPointerException
                                                                               at org.jivesoftware.smack.util.LazyStringBuilder.length(LazyStringBuilder.java:72)
                                                                               at org.jivesoftware.smack.util.XmlStringBuilder.length(XmlStringBuilder.java:329)
                                                                               at org.jivesoftware.smack.util.LazyStringBuilder.length(LazyStringBuilder.java:72)
                                                                               at org.jivesoftware.smack.util.LazyStringBuilder.toString(LazyStringBuilder.java:100)
                                                                               at org.jivesoftware.smack.util.XmlStringBuilder.toString(XmlStringBuilder.java:344)
                                                                               at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketWriter.writePackets(XMPPTCPConnection.java:1382)
                                                                               at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketWriter.access$2900(XMPPTCPConnection.java:1184)
                                                                               at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketWriter$1.run(XMPPTCPConnection.java:1232)
                                                                               at java.lang.Thread.run(Thread.java:841)
07-02 10:53:21.772 17715-21701/com.softdew.orahi D/QBASDK: Starrting recoonect
07-02 10:53:21.773 17715-21701/com.softdew.orahi I/ChatService: connectionClosedOnError: null

**Comment by Rhefew** [comment]
@QuickBlox-team Hello, same happening to me running quickblox sdk 2.5.2
the error is the following 
`com.quickblox.core.exception.QBResponseException: No response received within reply timeout. Timeout was 5000ms (~5s). Used filter: AndFilter: (FromMatchesFilter (full): 35265_577a58afa28f9a124700000c@muc.chat.quickblox.com/10913617, StanzaTypeFilter: org.jivesoftware.smack.packet.Presence).`

I'm facing this since last thursday after Joining a Group Chat, thanks in advance.

**Comment by Hemant0601** [comment]
@Rhefew just add below code in ChatService constructor, it helped me

`private ChatService() {
        try {
            chatService = QBChatService.getInstance();
            QBSettings.getInstance().setLogLevel(LogLevel.DEBUG);
            chatService.setDebugEnabled(true);
            chatService.setDefaultPacketReplyTimeout(150000); //add this
            chatService.setDefaultConnectionTimeout(150000); //add this
            chatService.setUseStreamManagement(true);
            chatService.addConnectionListener(chatConnectionListener);
        } catch (Exception e) {

        }
    }`

**Comment by akbarsha03** [comment]
@Hemant0601 I'm also having the pro account. As you said **QuickBlox** is actually a **BlackBox**. You'll never know what happens when you call a method. I tried your solution but no luck. The same exception happens to me when the admin of the group chat tries to remove a user. Right after removing a user the admin's connection gets disconnected and he no longer receives any chat messages or notification until he restart the app but other members could able to send/receive messages without any issue. All the implementation for the group chat was working fine but I really doubt myself now that something wouldn't have been done properly. **Any help on sample snippet to show "how to remove a user from quickblox" would be appreciable**.

**Comment by Hemant0601** [comment]
@akbarsha03 The removing user from a group is perfectly working fine for me. I am using the following code for this.

`public void removeFromGroup(final Integer id, final QBDialog qbDialog, Object... values) {
        try {
            QBRequestUpdateBuilder requestBuilder = new QBRequestUpdateBuilder();
            // requestBuilder.push("occupants_ids", 378); // add another users

            requestBuilder.pullAll("occupants_ids", values); // Remove yourself (user with ID 22)
            groupChatManager = QBChatService.getInstance().getGroupChatManager();

            groupChatManager.updateDialog(qbDialog, requestBuilder, new QBEntityCallback<QBDialog>() {
                @Override
                public void onSuccess(QBDialog qbDialog, Bundle bundle) {
                    Log.v(TAG, "Removing success");
                    OPref.saveData(OPref.LAST_DIALOG_UP_TIME, 0l);
                    // sendRiderChangeMsg(id, "removed");
                }

                @Override
                public void onError(QBResponseException e) {
                    Log.v(TAG, "Removing Failure" + e.getMessage() + "qbDialog" + qbDialog.getUserId());

                }
            });
        } catch (Exception e) {
            e.printStackTrace();
            recreateSession();

        }

    }`

**Comment by akbarsha03** [comment]
@Hemant0601 Thank you so much for the snippet. I also figured out that i'm sending a **null** in one of the **QBChatMessage** attribute. Its bad that we're not getting any kind of particular exception where it happens.

**Comment by Hemant0601** [comment]
@akbarsha03 thats what community is for "Sharing" :). Let me know if you face any other issue, I might help in that case too, currently I am also facing a serious issue, hope I get answer for that soon :)

**Comment by vfite** [comment]
Guys, to keep chat connection consistent you can use these settings:
https://quickblox.com/developers/Android_XMPP_Chat_Sample#Prepare_Chat_service. 
As for sending  custom property as null in message, can you pls provide code snippet and logs to look at issue ?
