### ISSUE TITLE
Unsubscribe from push notifications failed 404

### ISSUE THREAD

**Issue by yolapop** [QuickBlox/quickblox-android-sdk#251]
Hi, why can't I unsubscribe from push notification? The API call was returning HTTP 404. Please check this

``` java

07-19 16:29:33.408 27382-30334/com D/QBASDK: =========================================================
                                                                    === REQUEST ==== 11b3f621-2288-499a-be27-a567a48c492c ===
                                                                    REQUEST
                                                                        GET https://api.quickblox.com/subscriptions.json
                                                                    HEADERS
                                                                        QuickBlox-REST-API-Version=0.1.1
                                                                        QB-SDK=Android 2.5.2
                                                                        QB-Token=da46a98b156bd32934b661966509188bd1c24630
                                                                    PARAMETERS

                                                                    INLINE
                                                                        GET https://api.quickblox.com/subscriptions.json
07-19 16:29:34.646 27382-30334/com D/QBASDK: *********************************************************
                                                                    *** RESPONSE *** 11b3f621-2288-499a-be27-a567a48c492c ***
                                                                    STATUS : 404 
                                                                    HEADERS
                                                                        X-Runtime=0.061224
                                                                        Cache-Control=no-cache
                                                                        X-Rack-Cache=miss
                                                                        QuickBlox-REST-API-Version=0.1.1
                                                                        X-Android-Selected-Protocol=http/1.1
                                                                        X-UA-Compatible=IE=Edge,chrome=1
                                                                        QB-Token-ExpirationDate=2016-07-19 11:29:34 UTC
                                                                        Status=404 Not Found
                                                                        X-Request-Id=02d95db9f9edbf12b34a2a245ac0784a
                                                                        X-Android-Response-Source=NETWORK 404
                                                                        Connection=Close
                                                                        X-Android-Sent-Millis=1468920573985
                                                                        Content-Type=application/json; charset=utf-8
                                                                        Date=Tue, 19 Jul 2016 09:29:35 GMT
                                                                        Server=nginx/1.8.1
                                                                        Content-Length=1
                                                                        X-Android-Received-Millis=1468920574643
                                                                        Access-Control-Allow-Origin=*
                                                                    BODY
                                                                        ' '
07-19 16:29:34.647 27382-30334/com W/System.err: com.quickblox.core.exception.QBResponseException: Entity you are looking for was not found.
07-19 16:29:34.647 27382-30334/com W/System.err:     at com.quickblox.core.parser.QBJsonParser.parse(QBJsonParser.java:77)
07-19 16:29:34.647 27382-30334/com W/System.err:     at com.quickblox.core.Query.perform(Query.java:255)
07-19 16:29:34.647 27382-30334/com W/System.err:     at com.quickblox.messages.QBPushNotifications.getSubscriptions(QBPushNotifications.java:210)
07-19 16:29:34.647 27382-30334/com W/System.err:     at com.RegistrationIntentService.subscribeToQuickBloxPushNotifications(RegistrationIntentService.java:110)
07-19 16:29:34.648 27382-30334/com W/System.err:     at com.RegistrationIntentService.onHandleIntent(RegistrationIntentService.java:90)
07-19 16:29:34.648 27382-30334/com W/System.err:     at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:66)
07-19 16:29:34.648 27382-30334/com W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
07-19 16:29:34.648 27382-30334/com W/System.err:     at android.os.Looper.loop(Looper.java:148)
07-19 16:29:34.648 27382-30334/com W/System.err:     at android.os.HandlerThread.run(HandlerThread.java:61)

```

**Comment by yolapop** [comment]
Hi, any news about this? Our company is going to use Pro plan but we hit this problem. Can you help to resolve this?

**Comment by vfite** [comment]
Hi, as I see in logs you just retrieve subscriptions via GET method , but not delete. 
Response means that there are no subscriptions. Have a look at http://quickblox.com/developers/SimpleSample-messages_users-android for creating/deleting subscription.

**Comment by yolapop** [comment]
Yeah but the user has several subscriptions. You can see the response from `GET https://api.quickblox.com/subscriptions.json` is HTTP 404

**Comment by yolapop** [comment]
I had copied and pasted the same code as you pointed out.

**Comment by vfite** [comment]
Ok. How do y know that particular user has subscriptions ? Have y checked subscriptions on admin panel ? Could you provide screenshots ?  Did you create session token with or without user ?

**Comment by yolapop** [comment]
Yes the user has subscriptions from admin panel. If I give you a QB Token, can you check from your side that GET Subscriptions works? (Assuming you're willing to check within 2 hours)

**Comment by yolapop** [comment]
Okay, here's my code

First, I created session with user. Then...

```java

try {
    Log.v("mylog", "reg user id " + QBAuth.getSession().getUserId());
    // log -> reg user id 12212632
} catch (QBResponseException e) {
    e.printStackTrace();
}

try {
    ArrayList<QBSubscription> subscriptions = QBPushNotifications.getSubscriptions();
    for (QBSubscription subscription : subscriptions) {
        QBPushNotifications.deleteSubscription(subscription.getId());
        Log.v("mylog", "delete subscription " + subscription.getId());
    }
} catch (QBResponseException e0) {
    e0.printStackTrace();
    // this results in exception, stacktrace[1]
}

```

Stacktrace
[1]

```java

07-21 18:31:46.731 27816-28734/com W/System.err: com.quickblox.core.exception.QBResponseException: Entity you are looking for was not found.
07-21 18:31:46.731 27816-28734/com W/System.err:     at com.quickblox.core.parser.QBJsonParser.parse(QBJsonParser.java:89)
07-21 18:31:46.731 27816-28734/com W/System.err:     at com.quickblox.core.Query.perform(Query.java:261)
07-21 18:31:46.731 27816-28734/com W/System.err:     at com.quickblox.messages.QBPushNotifications.getSubscriptions(QBPushNotifications.java:210)
07-21 18:31:46.731 27816-28734/com W/System.err:     at com.services.RegistrationIntentService.subscribeToQuickBloxPushNotifications(RegistrationIntentService.java:119)
07-21 18:31:46.731 27816-28734/com W/System.err:     at com.services.RegistrationIntentService.onHandleIntent(RegistrationIntentService.java:94)
07-21 18:31:46.731 27816-28734/com W/System.err:     at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:66)
07-21 18:31:46.731 27816-28734/com W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
07-21 18:31:46.731 27816-28734/com W/System.err:     at android.os.Looper.loop(Looper.java:148)
07-21 18:31:46.731 27816-28734/com W/System.err:     at android.os.HandlerThread.run(HandlerThread.java:61)

```

**Comment by yolapop** [comment]
Screenshot admin

![screen shot 2016-07-21 at 6 37 55 pm](https://cloud.githubusercontent.com/assets/2100294/17021463/5a8993ac-4f72-11e6-9e1f-cd4c5593e3be.png)

**Comment by yolapop** [comment]
Hi, any news about this?

**Comment by yolapop** [comment]
Hi quickblox team, can you point out where I did something wrong?

**Comment by RomanPronin** [comment]
Use[ auto subscription](https://quickblox.com/developers/SimpleSample-messages_users-android#Setup_Push_Notifications_SDK_3.2_-_Auto_subscription) feature.
