### ISSUE TITLE
Gson crash in 2.6.1

### ISSUE THREAD

**Issue by sonnguyen0310** [QuickBlox/quickblox-android-sdk#260]
Hi everyone,
Just update my application to 2.6.1.
And get error when to get Dialog 

```
08-03 00:11:31.707 14298-14298/sng.com.studypro E/AndroidRuntime: FATAL EXCEPTION: main
                                                                Process: sng.com.studypro, PID: 14298
                                                                java.lang.IllegalArgumentException
                                                                    at com.google.gson.internal.$Gson$Preconditions.checkArgument($Gson$Preconditions.java:42)
                                                                    at com.google.gson.GsonBuilder.registerTypeAdapter(GsonBuilder.java:448)
                                                                    at com.quickblox.core.parser.QBJsonParser.buildGsonFromMap(QBJsonParser.java:123)
                                                                    at com.quickblox.core.parser.QBJsonParser.parseJsonResponse(QBJsonParser.java:104)
                                                                    at com.quickblox.core.parser.QBLimitedJsonParser.parseJsonResponse(QBLimitedJsonParser.java:22)
                                                                    at com.quickblox.core.parser.QBJsonParser.parse(QBJsonParser.java:91)
                                                                    at com.quickblox.core.Query$VersionEntityCallback.completedWithResponse(Query.java:393)
                                                                    at com.quickblox.core.Query.completedWithResponse(Query.java:277)
                                                                    at com.quickblox.core.server.HttpRequestRunnable$1.handleMessage(HttpRequestRunnable.java:42)
                                                                    at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                    at android.os.Looper.loop(Looper.java:145)
                                                                    at android.app.ActivityThread.main(ActivityThread.java:6837)
                                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                                    at java.lang.reflect.Method.invoke(Method.java:372)
                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
```

Any idea to help to resolve it ?

**Comment by vfite** [comment]
Could y provide full log from sdk request and response ?

**Comment by josesanchezgruposellcom** [comment]
I have the same issue on android.

Process: com.sellcom.apps.nissan.chat, PID: 29982
                                                                              java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/gson/GsonBuilder;
                                                                                  at com.quickblox.core.parser.QBJsonParser.parseJsonResponse(QBJsonParser.java:103)
                                                                                  at com.quickblox.core.parser.QBJsonParser.parse(QBJsonParser.java:91)
                                                                                  at com.quickblox.core.Query.parseAccountRequest(Query.java:339)
                                                                                  at com.quickblox.core.Query.access$000(Query.java:36)
                                                                                  at com.quickblox.core.Query$1.completedWithResponse(Query.java:229)
                                                                                  at com.quickblox.core.server.HttpRequestRunnable$1.handleMessage(HttpRequestRunnable.java:43)
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                  at android.os.Looper.loop(Looper.java:135)
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:5343)
                                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                                  at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)
                                                                               Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.gson.GsonBuilder" on path: DexPathList[[zip file "/data/app/com.sellcom.apps.nissan.chat-1/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
                                                                                  at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                                  at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                                                  at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                                                                  at com.quickblox.core.parser.QBJsonParser.parseJsonResponse(QBJsonParser.java:103) 
                                                                                  at com.quickblox.core.parser.QBJsonParser.parse(QBJsonParser.java:91) 
                                                                                  at com.quickblox.core.Query.parseAccountRequest(Query.java:339) 
                                                                                  at com.quickblox.core.Query.access$000(Query.java:36) 
                                                                                  at com.quickblox.core.Query$1.completedWithResponse(Query.java:229) 
                                                                                  at com.quickblox.core.server.HttpRequestRunnable$1.handleMessage(HttpRequestRunnable.java:43) 
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                  at android.os.Looper.loop(Looper.java:135) 
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:5343) 
                                                                                  at java.lang.reflect.Method.invoke(Native Method) 
                                                                                  at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905) 
                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700) 
                                                                              	Suppressed: java.lang.ClassNotFoundException: com.google.gson.GsonBuilder
                                                                                  at java.lang.Class.classForName(Native Method)
                                                                                  at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                                                                                  at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                                                                                  at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                                                                                  		... 14 more

**Comment by asinel** [comment]
Same issue

**Comment by RomanPronin** [comment]
In version 2.6.1 problem with com.google.gson.JsonDeserializer is already fixed.
