### ISSUE TITLE
Null pointer exception on QBVideoChatWebRTCSignalingManager.getSignaling(int)

### ISSUE THREAD

**Issue by rahulr4** [QuickBlox/quickblox-android-sdk#279]
I am facing this issue randomly. Sometimes it works, sometimes it crashes.
I am running it on Moto Turbo with Android Marshmellow

QBRTCSession newSessionWithOpponents = QBRTCClient
                        .getInstance(CallActivity.this).createNewSessionWithOpponents(opponents,
                                qbConferenceType);
                newSessionWithOpponents.getSessionDescription().setUserInfo(userInfoHashMap);

When the execution is at this code, this crash comes.
Please resolve it. Thank you

Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.app.serviceapp/com.app.serviceapp.videochat.CallActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'com.quickblox.chat.QBWebRTCSignaling com.quickblox.chat.QBVideoChatWebRTCSignalingManager.getSignaling(int)' on a null object reference
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2426)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2490)
       at android.app.ActivityThread.-wrap11(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1354)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5443)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'com.quickblox.chat.QBWebRTCSignaling com.quickblox.chat.QBVideoChatWebRTCSignalingManager.getSignaling(int)' on a null object reference
       at com.quickblox.videochat.webrtc.QBRTCSession.initSignallingWithOpponents(QBRTCSession.java:990)
       at com.quickblox.videochat.webrtc.QBRTCSession.<init>(QBRTCSession.java:149)
       at com.quickblox.videochat.webrtc.QBRTCClient.createNewSessionWithOpponents(QBRTCClient.java:187)
       at com.app.serviceapp.videochat.CallActivity.addConversationFragment(CallActivity.java:534)
       at com.app.serviceapp.videochat.CallActivity.onCreate(CallActivity.java:109)
       at android.app.Activity.performCreate(Activity.java:6259)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1130)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2379)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2490)
       at android.app.ActivityThread.-wrap11(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1354)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5443)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)

**Comment by tatanka987** [comment]
check login to the chat, before start call you must be logged to the chat

**Comment by rahulr4** [comment]
I am logged in, i have a session, both side users are logged in, have a session. This crash is random, and i have debugged inside the quickblox sdk also and i can see the opponent's ids.

**Comment by tatanka987** [comment]
hello @rahulr4, you must be logged to the **CHAT** but not to REST, please provide your code for login to the chat and full logs from start login  to getting this exception

**Comment by rahulr4** [comment]
I log in one i initiate the app using a service. User remains logged in always. Call come but somehow this error comes. This is not related to login because it is a null pointer on application instance. I internally debugged it. Sometimes it comes, sometimes it doesnt

**Comment by RomanPronin** [comment]
Use our latest version [SDK](https://quickblox.com/developers/Android#Download_Android_SDK)

**Comment by iflorit** [comment]
Still having the same problem using 3.3.1

java.lang.NullPointerException: Attempt to invoke virtual method 'com.quickblox.chat.QBWebRTCSignaling com.quickblox.chat.QBVideoChatWebRTCSignalingManager.getSignaling(int)' on a null object reference

Any update about this?
