### ISSUE TITLE
java.lang.NoSuchMethodError: QBJsonParser

### ISSUE THREAD

**Issue by pedrofsn** [QuickBlox/quickblox-android-sdk#284]
`java.lang.NoSuchMethodError: No virtual method initParser(Ljava/lang/reflect/Type;Ljava/lang/reflect/Type;Lcom/qb/gson/JsonDeserializer;)V in class Lcom/quickblox/core/parser/QBJsonParser; or its super classes (declaration of 'com.quickblox.core.parser.QBJsonParser' appears in /data/app/br.com.test.app-1/base.apk)`

I'm just using sample app code, this happens when i try to attach/take a photo.

**Comment by tatanka987** [comment]
hello @pedrofsn , please provide full logs of your request and response, additionaly provide full log of this error

**Comment by pedrofsn** [comment]
```
09-08 14:29:56.656 27664-27664/br.com.test.app E/AndroidRuntime: FATAL EXCEPTION: main
                                                                       Process: br.com.test.app, PID: 27664
                                                                       java.lang.NoSuchMethodError: No virtual method initParser(Ljava/lang/reflect/Type;Ljava/lang/reflect/Type;Lcom/qb/gson/JsonDeserializer;)V in class Lcom/quickblox/core/parser/QBJsonParser; or its super classes (declaration of 'com.quickblox.core.parser.QBJsonParser' appears in /data/app/br.com.test.app-1/base.apk)
                                                                           at com.quickblox.content.query.QueryBaseFile.<init>(QueryBaseFile.java:22)
                                                                           at com.quickblox.content.query.QueryCreateFile.<init>(QueryCreateFile.java:18)
                                                                           at com.quickblox.content.QBContent.createFile(QBContent.java:58)
                                                                           at com.quickblox.content.task.TaskEntityUploadFile.performTask(TaskEntityUploadFile.java:57)
                                                                           at com.quickblox.content.QBContent.uploadFileTask(QBContent.java:560)
                                                                           at br.com.provivencia.chat.utils.chat.ChatHelper.loadFileAsAttachment(ChatHelper.java:285)
                                                                           at br.com.provivencia.chat.ui.adapter.AttachmentPreviewAdapter.add(AttachmentPreviewAdapter.java:55)
                                                                           at br.com.provivencia.chat.ui.activity.ChatActivity.onImagePicked(ChatActivity.java:239)
                                                                           at com.quickblox.sample.core.utils.imagepick.GetFilepathFromUriTask.onResult(GetFilepathFromUriTask.java:80)
                                                                           at com.quickblox.sample.core.utils.imagepick.GetFilepathFromUriTask.onResult(GetFilepathFromUriTask.java:22)
                                                                           at com.quickblox.sample.core.async.BaseAsyncTask.onPostExecute(BaseAsyncTask.java:33)
                                                                           at android.os.AsyncTask.finish(AsyncTask.java:651)
                                                                           at android.os.AsyncTask.-wrap1(AsyncTask.java)
                                                                           at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:668)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                           at android.os.Looper.loop(Looper.java:148)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

```

**Comment by tatanka987** [comment]
br.com.test.app - this is not QuickBlox sample app, please review code of your app and change all imports from "com.qb.gson" to "com.google.gson"

**Comment by pedrofsn** [comment]
Ok, thanks.

**Comment by gadaramaulik123** [comment]
02-16 18:13:14.226 2640-2640/com.weapplinse.quickboxdemo E/AndroidRuntime: FATAL EXCEPTION: main
                                                                           Process: com.weapplinse.quickboxdemo, PID: 2640
                                                                           java.lang.NoSuchMethodError: com.quickblox.core.parser.QBJsonParser.initParser
                                                                               at com.quickblox.content.query.QueryBaseFile.<init>(QueryBaseFile.java:22)
                                                                               at com.quickblox.content.query.QueryCreateFile.<init>(QueryCreateFile.java:18)
                                                                               at com.quickblox.content.QBContent.createFile(QBContent.java:58)
                                                                               at com.quickblox.content.task.TaskEntityUploadFile.performTask(TaskEntityUploadFile.java:57)
                                                                               at com.quickblox.content.QBContent.uploadFileTask(QBContent.java:544)
                                                                               at com.weapplinse.quickboxdemo.chatingActivity.onActivityResult(chatingActivity.java:117)
                                                                               at android.app.Activity.dispatchActivityResult(Activity.java:5535)
                                                                               at android.app.ActivityThread.deliverResults(ActivityThread.java:3592)
                                                                               at android.app.ActivityThread.handleSendResult(ActivityThread.java:3639)
                                                                               at android.app.ActivityThread.access$1300(ActivityThread.java:155)
                                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1394)
                                                                               at android.os.Handler.dispatchMessage(Handler.java:110)
                                                                               at android.os.Looper.loop(Looper.java:193)
                                                                               at android.app.ActivityThread.main(ActivityThread.java:5341)
                                                                               at java.lang.reflect.Method.invokeNative(Native Method)
                                                                               at java.lang.reflect.Method.invoke(Method.java:515)
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:830)
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:646)
                                                                               at dalvik.system.NativeStart.main(Native Method)
