### ISSUE TITLE
Force close on android 4.1.2 

### ISSUE THREAD

**Issue by lordmen99** [QuickBlox/quickblox-android-sdk#289]
Hi team, i try on api 16 get this error = 

E/AndroidRuntime: FATAL EXCEPTION: main
                                                                       java.lang.NullPointerException
                                                                           at com.okbosnet.app.driver.fragment.VideoConversationFragment.fillVideoView(VideoConversationFragment.java:625)
                                                                           at com.okbosnet.app.driver.fragment.VideoConversationFragment.onRemoteVideoTrackReceive(VideoConversationFragment.java:432)
                                                                           at com.quickblox.videochat.webrtc.QBRTCSession$26.run(QBRTCSession.java:1228)
                                                                           at android.os.Handler.handleCallback(Handler.java:615)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:92)
                                                                           at android.os.Looper.loop(Looper.java:137)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:4810)
                                                                           at java.lang.reflect.Method.invokeNative(Native Method)
                                                                           at java.lang.reflect.Method.invoke(Method.java:511)
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:556)
                                                                           at dalvik.system.NativeStart.main(Native Method)
09-18 07:21:35.989 7880-8193/com.okbosnet.app.driver D/dalvikvm: GC_FOR_ALLOC freed 1698K, 20% free 22769K/28359K, paused 272ms, total 272ms

then app force close.. whats wrong with this?

**Comment by RomanPronin** [comment]
Looks something wrong with videoTrack. Look at our updated [videosample](https://github.com/QuickBlox/quickblox-android-sdk/tree/master/sample-videochat-webrtc).

**Comment by lordmen99** [comment]
please how code, for simple direct videocall in guide still make me confius. if have simple adapter, so i can easy add into any fragment

**Comment by RomanPronin** [comment]
Yet we don't have video adapter, you can look into our sample and Q-mun projects.

**Comment by vfite** [comment]
Closed for long inactivity
