### ISSUE TITLE
My Chat connection is getting Dropped again and again in Quickblox Chat ..What is the  issue ???

### ISSUE THREAD

**Issue by samarth220194** [QuickBlox/quickblox-android-sdk#325]
My chat app was working normally but now i am facing a issue ,my chat connection is getting dropped again and again ,My internet connection is proper ,all the other utilities of the app are working properly through internet connection .Please let me know if there is a server problem from quickblox .....

I am getting the following Chat Error in Logcat --

`11-04 17:41:27.494 32735-2354/com.baniaclothing.rang W/AbstractXMPPConnection: Connection closed with error
                                                                               java.net.SocketException: recvfrom failed: ECONNRESET (Connection reset by peer)
                                                                                   at libcore.io.IoBridge.maybeThrowAfterRecvfrom(IoBridge.java:545)
                                                                                   at libcore.io.IoBridge.recvfrom(IoBridge.java:509)
                                                                                   at java.net.PlainSocketImpl.read(PlainSocketImpl.java:489)
                                                                                   at java.net.PlainSocketImpl.access$000(PlainSocketImpl.java:46)
                                                                                   at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:241)
                                                                                   at java.io.InputStreamReader.read(InputStreamReader.java:233)
                                                                                   at java.io.BufferedReader.read(BufferedReader.java:325)
                                                                                   at org.jivesoftware.smack.util.ObservableReader.read(ObservableReader.java:41)
                                                                                   at org.kxml2.io.KXmlParser.fillBuffer(KXmlParser.java:1506)
                                                                                   at org.kxml2.io.KXmlParser.peekType(KXmlParser.java:986)
                                                                                   at org.kxml2.io.KXmlParser.next(KXmlParser.java:346)
                                                                                   at org.kxml2.io.KXmlParser.next(KXmlParser.java:310)
                                                                                   at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.parsePackets(XMPPTCPConnection.java:1169)
                                                                                   at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.access$300(XMPPTCPConnection.java:948)
                                                                                   at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader$1.run(XMPPTCPConnection.java:963)
                                                                                   at java.lang.Thread.run(Thread.java:841)
                                                                                Caused by: libcore.io.ErrnoException: recvfrom failed: ECONNRESET (Connection reset by peer)
                                                                                   at libcore.io.Posix.recvfromBytes(Native Method)
                                                                                   at libcore.io.Posix.recvfrom(Posix.java:141)
                                                                                   at libcore.io.BlockGuardOs.recvfrom(BlockGuardOs.java:164)
                                                                                   at libcore.io.IoBridge.recvfrom(IoBridge.java:506)
                                                                                   at java.net.PlainSocketImpl.read(PlainSocketImpl.java:489) 
                                                                                   at java.net.PlainSocketImpl.access$000(PlainSocketImpl.java:46) 
                                                                                   at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:241) 
                                                                                   at java.io.InputStreamReader.read(InputStreamReader.java:233) 
                                                                                   at java.io.BufferedReader.read(BufferedReader.java:325) 
                                                                                   at org.jivesoftware.smack.util.ObservableReader.read(ObservableReader.java:41) 
                                                                                   at org.kxml2.io.KXmlParser.fillBuffer(KXmlParser.java:1506) 
                                                                                   at org.kxml2.io.KXmlParser.peekType(KXmlParser.java:986) 
                                                                                   at org.kxml2.io.KXmlParser.next(KXmlParser.java:346) 
                                                                                   at org.kxml2.io.KXmlParser.next(KXmlParser.java:310) 
                                                                                   at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.parsePackets(XMPPTCPConnection.java:1169) 
                                                                                   at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.access$300(XMPPTCPConnection.java:948) 
                                                                                   at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader$1.run(XMPPTCPConnection.java:963) 
                                                                                   at java.lang.Thread.run(Thread.java:841) 
11-04 17:41:27.494 32735-2354/com.baniaclothing.rang D/QBASDK: Starrting recoonect
11-04 17:41:27.494 32735-2354/com.baniaclothing.rang I/VerboseQbChatConnectionListener: connectionClosedOnError(): recvfrom failed: ECONNRESET (Connection reset by peer)
11-04 17:41:27.504 32735-2354/com.baniaclothing.rang D/SMACK: XMPPConnection closed due to an exception (0)
11-04 17:41:27.514 32735-2354/com.baniaclothing.rang W/System.err: java.net.SocketException: recvfrom failed: ECONNRESET (Connection reset by peer)
11-04 17:41:27.514 32735-2354/com.baniaclothing.rang W/System.err:     at libcore.io.IoBridge.maybeThrowAfterRecvfrom(IoBridge.java:545)
11-04 17:41:27.514 32735-2354/com.baniaclothing.rang W/System.err:     at libcore.io.IoBridge.recvfrom(IoBridge.java:509)
11-04 17:41:27.514 32735-2354/com.baniaclothing.rang W/System.err:     at java.net.PlainSocketImpl.read(PlainSocketImpl.java:489)
11-04 17:41:27.514 32735-2354/com.baniaclothing.rang W/System.err:     at java.net.PlainSocketImpl.access$000(PlainSocketImpl.java:46)
11-04 17:41:27.514 32735-2354/com.baniaclothing.rang W/System.err:     at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:241)
11-04 17:41:27.514 32735-2354/com.baniaclothing.rang W/System.err:     at java.io.InputStreamReader.read(InputStreamReader.java:233)
11-04 17:41:27.514 32735-2354/com.baniaclothing.rang W/System.err:     at java.io.BufferedReader.read(BufferedReader.java:325)
11-04 17:41:27.514 32735-2354/com.baniaclothing.rang W/System.err:     at org.jivesoftware.smack.util.ObservableReader.read(ObservableReader.java:41)
11-04 17:41:27.514 32735-2354/com.baniaclothing.rang W/System.err:     at org.kxml2.io.KXmlParser.fillBuffer(KXmlParser.java:1506)
11-04 17:41:27.514 32735-2354/com.baniaclothing.rang W/System.err:     at org.kxml2.io.KXmlParser.peekType(KXmlParser.java:986)
11-04 17:41:27.514 32735-2354/com.baniaclothing.rang W/System.err:     at org.kxml2.io.KXmlParser.next(KXmlParser.java:346)
11-04 17:41:27.514 32735-2354/com.baniaclothing.rang W/System.err:     at org.kxml2.io.KXmlParser.next(KXmlParser.java:310)
11-04 17:41:27.514 32735-2354/com.baniaclothing.rang W/System.err:     at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.parsePackets(XMPPTCPConnection.java:1169)
11-04 17:41:27.514 32735-2354/com.baniaclothing.rang W/System.err:     at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.access$300(XMPPTCPConnection.java:948)
11-04 17:41:27.514 32735-2354/com.baniaclothing.rang W/System.err:     at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader$1.run(XMPPTCPConnection.java:963)
11-04 17:41:27.514 32735-2354/com.baniaclothing.rang W/System.err:     at java.lang.Thread.run(Thread.java:841)
11-04 17:41:27.514 32735-2354/com.baniaclothing.rang W/System.err: Caused by: libcore.io.ErrnoException: recvfrom failed: ECONNRESET (Connection reset by peer)
11-04 17:41:27.514 32735-2354/com.baniaclothing.rang W/System.err:     at libcore.io.Posix.recvfromBytes(Native Method)
11-04 17:41:27.514 32735-2354/com.baniaclothing.rang W/System.err:     at libcore.io.Posix.recvfrom(Posix.java:141)
11-04 17:41:27.514 32735-2354/com.baniaclothing.rang W/System.err:     at libcore.io.BlockGuardOs.recvfrom(BlockGuardOs.java:164)
11-04 17:41:27.514 32735-2354/com.baniaclothing.rang W/System.err:     at libcore.io.IoBridge.recvfrom(IoBridge.java:506)
11-04 17:41:27.514 32735-2354/com.baniaclothing.rang W/System.err: 	... 14 more`

**Comment by tatanka987** [comment]
@samarth220194 set Socket Timeout parameter 0 for disabling permanently reconnections for support chat connection:
QBChatService.ConfigurationBuilder builder = new QBChatService.ConfigurationBuilder();
builder.setSocketTimeout(0);
QBChatService.setConfigurationBuilder(builder);
for disabling permanently reconnections for support chat connection.
