### ISSUE TITLE
Crashing Unexpectedly

### ISSUE THREAD

**Issue by Hemant0601** [QuickBlox/quickblox-android-sdk#331]
Please look at the trace, can you tell me what went wrong for this.

Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'com.quickblox.chat.QBGroupChat com.quickblox.chat.QBGroupChatManager.getGroupChat(java.lang.String)' on a null object reference
       at com.quickblox.chat.model.QBChatDialog.initChat(SourceFile:399)
       at com.quickblox.chat.model.QBChatDialog.initChatFromRest(SourceFile:336)
       at com.quickblox.chat.model.QBDialogDeserializer.deserialize(SourceFile:114)
       at com.quickblox.chat.model.QBDialogDeserializer.deserialize(SourceFile:25)
       at com.google.gson.TreeTypeAdapter.read(SourceFile:58)
       at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(SourceFile:40)
       at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(SourceFile:81)
       at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(SourceFile:60)
       at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(SourceFile:95)
       at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(SourceFile:183)
       at com.google.gson.Gson.fromJson(SourceFile:805)
       at com.google.gson.Gson.fromJson(SourceFile:770)
       at com.google.gson.Gson.fromJson(SourceFile:719)
       at com.quickblox.core.parser.QBJsonParser.parseJsonResponse(SourceFile:110)
       at com.quickblox.core.parser.QBLimitedJsonParser.parseJsonResponse(SourceFile:22)
       at com.quickblox.core.parser.QBJsonParser.parse(SourceFile:91)
       at com.quickblox.core.Query$VersionEntityCallback.completedWithResponse(SourceFile:418)
       at com.quickblox.core.Query.completedWithResponse(SourceFile:297)
       at com.quickblox.core.server.HttpRequestRunnable$1.handleMessage(SourceFile:43)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:159)
       at android.app.ActivityThread.main(ActivityThread.java:5461)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:964)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:759)

**Comment by pelipetsaa** [comment]
Please give part of your source code.
You can use as example Simple Android Chat 
https://quickblox.com/developers/Android_XMPP_Chat_Sample

**Comment by Hemant0601** [comment]
QB changed a flag which was causing this, additional check fixed the issue
