### ISSUE TITLE
Camera Problem on Moverio BT-2000

### ISSUE THREAD

**Issue by Vol-i** [QuickBlox/quickblox-android-sdk#346]
Hi,

We are trying to use Epson Moverio BT-2000 smart glass with Quickblox but app crashes on SDK 3.2.0 when the incoming video call is answered. It works well on previous device Epson Moverio BT-200 but it seems like there is a problem with camera on BT-2000 device. Logcat log is as below.

Sdk version 2.3.3 is working but image is grayscale as discussed at #143 . But at newer SDK versions, It doesn't work at all.

Device Specs:
Android 4.0.4
1 GB Ram

Logcat:
`E/org.webrtc.Logging: VideoCapturerAndroid: startCapture failed
E/org.webrtc.Logging: VideoCapturerAndroid: java.lang.RuntimeException: setParameters failed
E/org.webrtc.Logging: VideoCapturerAndroid: java.lang.RuntimeException: setParameters failed
                          at android.hardware.Camera.native_setParameters(Native Method)
                          at android.hardware.Camera.setParameters(Camera.java:1405)
                          at org.webrtc.VideoCapturerAndroid.startPreviewOnCameraThread(VideoCapturerAndroid.java:455)
                          at org.webrtc.VideoCapturerAndroid.startCaptureOnCameraThread(VideoCapturerAndroid.java:353)
                          at org.webrtc.VideoCapturerAndroid.access$800(VideoCapturerAndroid.java:42)
                          at org.webrtc.VideoCapturerAndroid$5.run(VideoCapturerAndroid.java:290)
                          at android.os.Handler.handleCallback(Handler.java:605)
                          at android.os.Handler.dispatchMessage(Handler.java:92)
                          at android.os.Looper.loop(Looper.java:137)
                          at android.os.HandlerThread.run(HandlerThread.java:60)`

**Comment by pelipetsaa** [comment]
This means that there were some parameter invalid or not supported.
Please give log before the crash.

**Comment by tatanka987** [comment]
please try our latest [SDK](https://quickblox.com/developers/Android) with updated WebRTC lib

**Comment by tatanka987** [comment]
closed, long time inactivity
