### ISSUE TITLE
QuickBlox Push Notification Crash $Gson$Preconditions.checkArgument

### ISSUE THREAD

**Issue by omert742** [QuickBlox/quickblox-android-sdk#354]
0
down vote
favorite
i am trying to use quickblox push notification by the guild at their site and i allready checked myself so many times that i did every step correctly but i am still getting this crash :

errorReport************ CAUSE OF ERROR ************

                                   java.lang.IllegalArgumentException
                                       at com.google.gson.internal.$Gson$Preconditions.checkArgument($Gson$Preconditions.java:42)
                                       at com.google.gson.GsonBuilder.registerTypeAdapter(GsonBuilder.java:448)
                                       at com.quickblox.core.parser.QBJsonParser.buildGsonFromMap(QBJsonParser.java:123)
                                       at com.quickblox.core.parser.QBJsonParser.parseJsonResponse(QBJsonParser.java:104)
                                       at com.quickblox.core.parser.QBJsonParser.parse(QBJsonParser.java:91)
                                       at com.quickblox.core.Query$VersionEntityCallback.completedWithResponse(Query.java:393)
                                       at com.quickblox.core.Query.completedWithResponse(Query.java:277)
                                       at com.quickblox.core.server.HttpRequestRunnable$1.handleMessage(HttpRequestRunnable.java:42)
                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                       at android.os.Looper.loop(Looper.java:145)
                                       at android.app.ActivityThread.main(ActivityThread.java:6939)
                                       at java.lang.reflect.Method.invoke(Native Method)
                                       at java.lang.reflect.Method.invoke(Method.java:372)
                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
I search up alot but i didn't got a answer ,ty .

**Comment by pelipetsaa** [comment]
please give your source code and text of the push notification

**Comment by pelipetsaa** [comment]
Close. long time inactivity
