### ISSUE TITLE
Application Crash on qbChatDialog.sendMessage(chatMessage);

### ISSUE THREAD

**Issue by amitpadmani** [QuickBlox/quickblox-android-sdk#377]
**Environment details**
*(Operating system, browser information, SDK version)*
Android, SDK: 3.20

**Expected behavior**
when I login in an application and chat with other users it's working fine but once I exit from an application and start again and sending a message in chat dialog application crash.

**Actual behavior**
application should not crash. 

**Logs**
*(please, use github [gist](https://gist.github.com/))*

FATAL EXCEPTION: main
                                                              Process: com.bhads.ibuy, PID: 7295
                                                              java.lang.IllegalStateException: Could not execute method for android:onClick
                                                                  at android.support.v7.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:293)
                                                                  at android.view.View.performClick(View.java:4780)
                                                                  at android.view.View$PerformClick.run(View.java:19866)
                                                                  at android.os.Handler.handleCallback(Handler.java:739)
                                                                  at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                  at android.os.Looper.loop(Looper.java:135)
                                                                  at android.app.ActivityThread.main(ActivityThread.java:5254)
                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                  at java.lang.reflect.Method.invoke(Method.java:372)
                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
                                                               Caused by: java.lang.reflect.InvocationTargetException
                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                  at java.lang.reflect.Method.invoke(Method.java:372)
                                                                  at android.support.v7.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:288)
                                                                  at android.view.View.performClick(View.java:4780) 
                                                                  at android.view.View$PerformClick.run(View.java:19866) 
                                                                  at android.os.Handler.handleCallback(Handler.java:739) 
                                                                  at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                  at android.os.Looper.loop(Looper.java:135) 
                                                                  at android.app.ActivityThread.main(ActivityThread.java:5254) 
                                                                  at java.lang.reflect.Method.invoke(Native Method) 
                                                                  at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903) 
                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698) 
                                                               Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.quickblox.chat.QBAbstractChat.sendMessage(com.quickblox.chat.model.QBChatMessage)' on a null object reference
                                                                  at com.quickblox.chat.model.QBChatDialog.sendMessage(SourceFile:506)
                                                                  at com.bhads.ibuy.ui.activity.ChatActivity.sendChatMessage(ChatActivity.java:364)
                                                                  at com.bhads.ibuy.ui.activity.ChatActivity.onSendChatClick(ChatActivity.java:287)
                                                                  at java.lang.reflect.Method.invoke(Native Method) 
                                                                  at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                  at android.support.v7.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:288) 
                                                                  at android.view.View.performClick(View.java:4780) 
                                                                  at android.view.View$PerformClick.run(View.java:19866) 
                                                                  at android.os.Handler.handleCallback(Handler.java:739) 
                                                                  at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                  at android.os.Looper.loop(Looper.java:135) 
                                                                  at android.app.ActivityThread.main(ActivityThread.java:5254) 
                                                                  at java.lang.reflect.Method.invoke(Native Method) 
                                                                  at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903) 
                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698) 

**Steps to reproduce the behavior**
   -> Login in application 
   -> sending message in the user dialog
   -> exit from application (kill from background also)
   -> start application again
   -> go to the dialog list activity and select dialog
   -> type message and click on send button , APPLICATION IS CRASH

**Any others comments?**
I also did reloginToChat(user) and it gives Success response.
and also set following properties in chat helper class

        qbChatService.setDefaultPacketReplyTimeout(150000); //add this
        qbChatService.setDefaultConnectionTimeout(150000);
        qbChatService.setDefaultAutoSendPresenceInterval(60);

        QBChatService.ConfigurationBuilder chatServiceConfigurationBuilder = new QBChatService.ConfigurationBuilder();
        chatServiceConfigurationBuilder.setSocketTimeout(60); 
        chatServiceConfigurationBuilder.setKeepAlive(true); 
        chatServiceConfigurationBuilder.setUseTls(true); 
        QBChatService.setConfigurationBuilder(chatServiceConfigurationBuilder);

**Comment by tatanka987** [comment]
hello @amitpadmani, please fallow [our documentation ](https://quickblox.com/developers/Android_XMPP_Chat_Sample#QBChatDialog_model). In your case you have to 

> To make QBChatDialog active again after next login, you just need to initialize it with active chat service
