### ISSUE TITLE
java.lang.ClassNotFoundException: Didn't find class "com.quickblox.messages.services.SubscribeTaskManager"

### ISSUE THREAD

**Issue by lakshayjuneja** [QuickBlox/quickblox-android-sdk#398]
USER_COMMENT=null
STACK_TRACE=java.lang.RuntimeException: Unable to instantiate service com.quickblox.messages.services.SubscribeTaskManager: java.lang.ClassNotFoundException: Didn't find class "com.quickblox.messages.services.SubscribeTaskManager" on path: DexPathList[[zip file "/data/app/com.package/base.apk"],nativeLibraryDirectories=[/data/app/com.package-1/lib/arm, /vendor/lib, /system/lib]]
at android.app.ActivityThread.handleCreateService(ActivityThread.java:2779)
at android.app.ActivityThread.access$1900(ActivityThread.java:154)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1404)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5294)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.quickblox.messages.services.SubscribeTaskManager" on path: DexPathList[[zip file "/data/app/com.package-1/base.apk"],nativeLibraryDirectories=[/data/app/com.package-1/lib/arm, /vendor/lib, /system/lib]]
at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
at android.app.ActivityThread.handleCreateService(ActivityThread.java:2776)
... 9 more
Suppressed: java.lang.NoClassDefFoundError: com.quickblox.messages.services.SubscribeTaskManager
at dalvik.system.DexFile.defineClassNative(Native Method)
at dalvik.system.DexFile.defineClass(DexFile.java:226)
at dalvik.system.DexFile.loadClassBinaryName(DexFile.java:219)
at dalvik.system.DexPathList.findClass(DexPathList.java:321)
at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:54)
... 12 more
Suppressed: java.lang.ClassNotFoundException: com.quickblox.messages.services.SubscribeTaskManager
at java.lang.Class.classForName(Native Method)
at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
... 11 more
Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available

**Comment by tatanka987** [comment]
hello @lakshayjuneja, sorry for delayed response, if you use ProGuard, try to add next line 
-keep class com.quickblox.messages.services.SubscribeTaskManager { *; }  for excluding this class from obfuscation

**Comment by RomanPronin** [comment]
Long time inactivity

**Comment by Nikhil-z** [comment]
@lakshayjuneja  Have you found any solution?. I'm also having the same issue and I'm not using any ProGaurd feature in my project.
