### ISSUE TITLE
Session creation error

### ISSUE THREAD

**Issue by ahsanzia341** [QuickBlox/quickblox-android-sdk#407]
java.lang.NoSuchMethodError: No virtual method getUserId()Ljava/lang/Integer; in class Lcom/quickblox/auth/session/QBSession; or its super classes (declaration of 'com.quickblox.auth.session.QBSession' appears in /data/app/com.example.ast.whatthelove-1/split_lib_dependencies_apk.apk:classes5.dex)
                                                                                 at com.quickblox.messages.QBPushNotifications$1.onSessionCreated(Unknown Source)
                                                                                 at com.quickblox.auth.session.QBSessionManager$1.run(Unknown Source)
                                                                                 at android.os.Handler.handleCallback(Handler.java:815)
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:104)
                                                                                 at android.os.Looper.loop(Looper.java:207)
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:5728)
                                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)

Code:

 public void QBinit(){
        QBSettings.getInstance().init(getApplicationContext(), APP_ID, AUTH_KEY, AUTH_SECRET);
        QBSettings.getInstance().setAccountKey(ACCOUNT_KEY);
    }
    public void callListener(){
        QBChatService.getInstance().getVideoChatWebRTCSignalingManager()
                .addSignalingManagerListener(new QBVideoChatSignalingManagerListener() {
                    @Override
                    public void signalingCreated(QBSignaling qbSignaling, boolean createdLocally) {
                        if (!createdLocally) {
                            QBRTCClient.getInstance(getApplicationContext()).addSignaling((QBWebRTCSignaling) qbSignaling);
                        }
                    }
                });
    }
 
    public void createSession(String login, String password){
        final QBUser user = new QBUser(login, password);
        user.setEmail("xggamer3001@yahoo.com");
        Performer<QBSession> session = QBAuth.createSession(user);
        session.performAsync(new QBEntityCallback<QBSession>() {
            @Override
            public void onSuccess(QBSession qbSession, Bundle bundle) {
                // INIT CHAT SERVICE
                chatService = QBChatService.getInstance();

                // LOG IN CHAT SERVICE
                chatService.login(user, new QBEntityCallback<QBUser>() {

                    @Override
                    public void onSuccess(QBUser qbUser, Bundle bundle) {
                        callListener();
                    }

                    @Override
                    public void onError(QBResponseException errors) {
                        MyToast.makeToastLong(VideoChatActivity.this, errors.getMessage());
                    }
                });
            }

            @Override
            public void onError(QBResponseException e) {
                Log.d("Error", e.getMessage());
                MyToast.makeToastLong(VideoChatActivity.this, e.getMessage());
            }
        });
    }

**Comment by tatanka987** [comment]
looks like ProGuard obfuscated this method, try to add next string for skipping QBSession class in ProGuard's config file

-keep class com.quickblox.auth.session.QBSession { *; }

**Comment by ahsanzia341** [comment]
@tatanka987 ... didnt worked :(

**Comment by bhaveshintorque** [comment]
@tatanka987  i have facing same issue have u got any solution?

**Comment by alexanderkoqb** [comment]
Hey @ahsanzia341 
Since it's been a while and if you're still being experiencing analogous troubles with the newer SDK (WebRTC) versions, you can contact QB here: https://assist.quickblox.com/index.php?/Base/UserRegistration/Register or raise a new issue in corresponding GitHub project.
Best!
