### ISSUE TITLE
java.lang.RuntimeException: Unable to start service com.wtf.services.CallService (Android)

### ISSUE THREAD

**Issue by iosgnanavel** [QuickBlox/quickblox-android-sdk#442]
Hi team,
   Following error occur while click to open app  **or**  Kill app from recent list.Call service start like sample any issues in that code.

**Issue:**
java.lang.RuntimeException: Unable to start service com.wtf.services.CallService@6de28b9 with Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10000000 cmp=com.wtf/.activity.SplashActivity launchParam=MultiScreenLaunchParams { mDisplayId=0 mFlags=0 } }: java.lang.IllegalArgumentException: Receiver not registered: com.wtf.utils.ChatPingAlarmManager$1@515e4fe
at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3705)
at android.app.ActivityThread.-wrap23(ActivityThread.java)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1736)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:154)
at android.app.ActivityThread.main(ActivityThread.java:6682)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
Caused by: java.lang.IllegalArgumentException: Receiver not registered: com.wtf.utils.ChatPingAlarmManager$1@515e4fe
at android.app.LoadedApk.forgetReceiverDispatcher(LoadedApk.java:1054)
at android.app.ContextImpl.unregisterReceiver(ContextImpl.java:1359)
at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:651)
at com.wtf.utils.ChatPingAlarmManager.onDestroy(ChatPingAlarmManager.java:110)
at com.wtf.services.CallService.destroyRtcClientAndChat(CallService.java:214)
at com.wtf.services.CallService.onTaskRemoved(CallService.java:254)
at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3690)
... 8 more

**Comment by tatanka987** [comment]
java.lang.IllegalArgumentException: Receiver not registered: com.wtf.utils.ChatPingAlarmManager$1@515e4fe   this error not from QuickBlox Android SDK. Please read manuals for work with AlarmManager
