### ISSUE TITLE
About connectionClosedOnError

### ISSUE THREAD

**Issue by jwzhuang** [QuickBlox/quickblox-android-sdk#482]
After QBSystemMessagesManager.sendSystemMessage, it will trigger ConnectionListener.connectionClosedOnError 

connectionClosedOnError(Exception e) :
`
java.lang.NullPointerException: Attempt to invoke interface method 'int java.lang.CharSequence.length()' on a null object reference
`

Logcat:
`
W/XMPPTCPConnection: shutdownDone was not marked as successful by the writer thread
    org.jivesoftware.smack.SmackException$NoResponseException: No response received within reply timeout. Timeout was 10000ms (~10s). Used filter: No filter used or filter was 'null'.
        at org.jivesoftware.smack.SynchronizationPoint.checkForResponse(Unknown Source)
        at org.jivesoftware.smack.SynchronizationPoint.checkIfSuccessOrWait(Unknown Source)
        at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketWriter.shutdown(Unknown Source)
        at org.jivesoftware.smack.tcp.XMPPTCPConnection.shutdown(Unknown Source)
        at org.jivesoftware.smack.tcp.XMPPTCPConnection.instantShutdown(Unknown Source)
        at org.jivesoftware.smack.tcp.XMPPTCPConnection.notifyConnectionError(Unknown Source)
        at org.jivesoftware.smack.tcp.XMPPTCPConnection.access$2900(Unknown Source)
        at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketWriter.writePackets(Unknown Source)
        at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketWriter.access$3000(Unknown Source)
        at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketWriter$1.run(Unknown Source)
        at java.lang.Thread.run(Thread.java:818)
W/AbstractXMPPConnection: Connection closed due to inactivity server
D/SMACK: XMPPConnection closed due to non response (0)
`

*(Operating system, browser information, SDK version)*
Android: 6.0
SDK version : 3.5.0

**Comment by pumatus** [comment]
so easy

**Comment by QB-nikolay-zolotarov** [comment]
Hello QuickBlox customer,

This is Nikolay from QuickBlox support.

The issue was closed as it is outdated.

Please update the SDK to the latest version:
[https://github.com/QuickBlox/quickblox-android-sdk-releases/releases/tag/3.9.11](https://github.com/QuickBlox/quickblox-android-sdk-releases/releases/tag/3.9.11)

Additionally, please check our new samples:
[https://docs.quickblox.com/docs/code-samples#chat-samples](https://docs.quickblox.com/docs/code-samples#chat-samples)

If it is still relevant after reviewing the updated information, feel free to open a new issue.

Have a nice day.
