### ISSUE TITLE
gson null exceptions

### ISSUE THREAD

**Issue by rahultailor** [QuickBlox/quickblox-android-sdk#489]
I solved this issue by reverting back to gson version 2.6.2. But Now I have to use gson 2.8.2 because other sdk are using this version. Any solution other then reverting back.

Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'long java.util.Date.getTime()' on a null object reference
at java.util.Calendar.setTime(Calendar.java:1195)
at java.text.SimpleDateFormat.formatImpl(SimpleDateFormat.java:518)
at java.text.SimpleDateFormat.format(SimpleDateFormat.java:820)
at java.text.DateFormat.format(DateFormat.java:314)
at com.google.gson.DefaultDateTypeAdapter.write(DefaultDateTypeAdapter.java:88)
at com.google.gson.DefaultDateTypeAdapter.write(DefaultDateTypeAdapter.java:40)
at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69)
at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:125)
at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:243)
at com.google.gson.Gson.toJson(Gson.java:669)
at com.google.gson.Gson.toJson(Gson.java:648)
at com.google.gson.Gson.toJson(Gson.java:603)
at com.google.gson.Gson.toJson(Gson.java:583)
at com.quickblox.auth.session.b.save(Unknown Source)
at com.quickblox.auth.session.QBSessionManager.setActiveSession(Unknown Source)
at com.quickblox.auth.session.QBSessionJsonParser.extractEntity(Unknown Source)
at com.quickblox.auth.session.QBSessionJsonParser.extractEntity(Unknown Source)
at com.quickblox.core.parser.QBJsonParser.parse(Unknown Source)
at com.quickblox.auth.session.Query$VersionEntityCallback.completedWithResponse(Unknown Source)
at com.quickblox.auth.session.Query.completedWithResponse(Unknown Source)
at com.quickblox.core.server.HttpRequestRunnable$1.handleMessage(Unknown Source)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5254)
at java.lang.reflect.Method.invoke(Method.java)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

**Comment by tatanka987** [comment]
which version of QuickBlox Android SDK do you use?

**Comment by rahultailor** [comment]
compile 'com.quickblox:quickblox-android-sdk-messages:3.5.0'
compile 'com.quickblox:quickblox-android-sdk-core:3.5.0'
compile 'com.quickblox:quickblox-android-sdk-content:3.5.0'
compile('com.quickblox:quickblox-android-sdk-chat:3.5.0') {
    transitive = true
}
compile 'com.google.code.gson:gson:2.8.2'

**Comment by tatanka987** [comment]
in latest version (3.5.1) we updated Gson lib to 2.8.2, so try use it. Looks like other lib in your project uses Gson lib version 2.8.1, check it by reviewing "External Libraries" in Android Studio

**Comment by rahultailor** [comment]
@tatanka987  Thankyou. Its working fine now.
