### ISSUE TITLE
App Crash when calling method  chatDialog.getLastMessageUserId(); on newly created ChatDialog with no last message

### ISSUE THREAD

**Issue by Shahjahan786** [QuickBlox/quickblox-android-sdk#502]
2-07 06:55:14.568 17364-17364/com.nayapay.app E/AndroidRuntime: FATAL EXCEPTION: main
                                                                 Process: com.nayapay.app, PID: 17364
                                                                 java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
                                                                     at com.nayapay.app.chat.ui.adapter.DialogsAdapter.prepareTextLastMessage(DialogsAdapter.java:109)
                                                                     at com.nayapay.app.chat.ui.adapter.DialogsAdapter.getView(DialogsAdapter.java:61)
                                                                     at android.widget.HeaderViewListAdapter.getView(HeaderViewListAdapter.java:220)
                                                                     at android.widget.AbsListView.obtainView(AbsListView.java:2365)
                                                                     at android.widget.ListView.makeAndAddView(ListView.java:2052)
                                                                     at android.widget.ListView.fillDown(ListView.java:786)
                                                                     at android.widget.ListView.fillSpecific(ListView.java:1494)
                                                                     at android.widget.ListView.layoutChildren(ListView.java:1790)
                                                                     at android.widget.AbsListView.onLayout(AbsListView.java:2164)
                                                                     at android.view.View.layout(View.java:19659)
                                                                     at android.view.ViewGroup.layout(ViewGroup.java:6075)
                                                                     at com.orangegangsters.github.swipyrefreshlayout.library.SwipyRefreshLayout.onLayout(SwipyRefreshLayout.java:583)
                                                                     at android.view.View.layout(View.java:19659)
                                                                     at android.view.ViewGroup.layout(ViewGroup.java:6075)
                                                                     at android.support.design.widget.CoordinatorLayout.layoutChild(CoordinatorLayout.java:1166)
                                                                     at android.support.design.widget.CoordinatorLayout.onLayoutChild(CoordinatorLayout.java:851)
                                                                     at android.support.design.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:870)
                                                                     at android.view.View.layout(View.java:19659)
                                                                     at android.view.ViewGroup.layout(ViewGroup.java:6075)
                                                                     at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1767)
                                                                     at android.view.View.layout(View.java:19659)
                                                                     at android.view.ViewGroup.layout(ViewGroup.java:6075)
                                                                     at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1083)
                                                                     at android.view.View.layout(View.java:19659)
                                                                     at android.view.ViewGroup.layout(ViewGroup.java:6075)
                                                                     at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
                                                                     at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
                                                                     at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
                                                                     at android.view.View.layout(View.java:19659)
                                                                     at android.view.ViewGroup.layout(ViewGroup.java:6075)
                                                                     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                     at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                     at android.view.View.layout(View.java:19659)
                                                                     at android.view.ViewGroup.layout(ViewGroup.java:6075)
                                                                     at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
                                                                     at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
                                                                     at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
                                                                     at android.view.View.layout(View.java:19659)
                                                                     at android.view.ViewGroup.layout(ViewGroup.java:6075)
                                                                     at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:1172)
                                                                     at android.view.View.layout(View.java:19659)
                                                                     at android.view.ViewGroup.layout(ViewGroup.java:6075)
                                                                     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                     at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                     at android.view.View.layout(View.java:19659)
                                                                     at android.view.ViewGroup.layout(ViewGroup.java:6075)
                                                                     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                     at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                     at android.view.View.layout(View.java:19659)
                                                                     at android.view.ViewGroup.layout(ViewGroup.java:6075)
                                                                     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                     at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                     at android.view.View.layout(View.java:19659)
                                                                     at android.view.ViewGroup.layout(ViewGroup.java:6075)
                                                                     at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
                                                                     at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
                                                                     at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
                                                                     at android.view.View.layout(View.java:19659)
                                                                     at android.view.ViewGroup.layout(ViewGroup.java:6075)
                                                                     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                     at android.widget.FrameLayout.onLayout(FrameLayout.java:261)

**Comment by Shahjahan786** [comment]
Any update on this?

**Comment by tatanka987** [comment]
NullPointerException is programmer's mistake, review your code for searching issue.

**Comment by Shahjahan786** [comment]
Actually signature of method is **Integer getLastMessageUserId()** and when there is no last message in dialog it returns null and I was assigning it to **int** so unboxing produced null pointer exception.
