### ISSUE TITLE
After updating my library App get crash 

### ISSUE THREAD

**Issue by ominfowave** [QuickBlox/quickblox-android-sdk#505]
My application compileSdkVersion version and library:
    compileSdkVersion 27
    buildToolsVersion '27.0.2'
    compile 'com.android.support:multidex:1.0.1'
    compile fileTree(include: ['*.jar'], dir: 'libs')
    testCompile 'junit:junit:4.12'
    compile 'com.android.support:appcompat-v7:27.0.2'
    compile 'com.android.support:design:27.0.2'
    compile 'com.android.support:support-v4:27.0.2'
    compile 'com.android.support:recyclerview-v7:27.0.2'
    compile 'com.android.support:cardview-v7:27.0.2'
    compile files('libs/httpclient-osgi-4.3.jar')
    compile 'com.google.android.gms:play-services-places:11.6.2'
    compile 'com.google.android.gms:play-services-location:11.6.2'
    compile 'com.google.firebase:firebase-messaging:11.6.2'
    compile 'com.android.support.constraint:constraint-layout:1.0.2'
    compile 'com.android.volley:volley:1.0.0'
    compile 'com.google.code.gson:gson:2.8.2'
    compile 'com.facebook.android:facebook-android-sdk:4.21.1'
    compile 'com.squareup.picasso:picasso:2.5.2'
    compile 'com.github.bumptech.glide:glide:3.7.0'
    compile('com.crashlytics.sdk.android:crashlytics:2.6.8@aar') {
        transitive = true;
    }
    compile 'com.quickblox:quickblox-android-sdk-core:3.5.2'
    compile 'com.quickblox:quickblox-android-sdk-videochat-webrtc:3.5.2'
    compile 'com.quickblox:quickblox-android-sdk-messages:3.5.2'

**Did this work before?**
yes work with older version of google library
    compile 'com.google.android.gms:play-services-places:11.0.2'
    compile 'com.google.android.gms:play-services-location:11.0.2'
    compile 'com.google.firebase:firebase-messaging:11.0.2'

**Logs**
FATAL EXCEPTION: 
Process: com.vamplife.android, PID: 2502
java.lang.RuntimeException: An error occured while executing doInBackground()
at android.os.AsyncTask$3.done(AsyncTask.java:304)
at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
at java.util.concurrent.FutureTask.run(FutureTask.java:242)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
 at java.lang.Thread.run(Thread.java:818)
 Caused by: java.lang.NoSuchMethodError: No static method getNoBackupFilesDir(Landroid/content/Context;)Ljava/io/File; in class Lcom/google/android/gms/common/util/zzu; or its super classes (declaration of 'com.google.android.gms.common.util.zzu' appears in /data/app/com.vamplife.android-1/split_lib_dependencies_apk.apk)
at com.google.android.gms.iid.zzh.<init>(Unknown Source)
at com.google.android.gms.iid.zzh.<init>(Unknown Source)
at com.google.android.gms.iid.InstanceID.getInstance(Unknown Source)
 at com.google.android.gms.iid.InstanceID.getInstance(Unknown Source)
at com.quickblox.messages.services.a.c.<init>(Unknown Source)
at com.quickblox.messages.services.a.d.a(Unknown Source)
at com.quickblox.messages.services.SubscribeService.a(Unknown Source)
at com.quickblox.messages.services.SubscribeService.a(Unknown Source)
 at com.quickblox.messages.services.SubscribeService.b(Unknown Source)
at com.quickblox.messages.services.SubscribeService.c(Unknown Source)
at com.quickblox.messages.services.SubscribeService.onHandleWork(Unknown Source)
at android.support.v4.app.JobIntentService$CommandProcessor.doInBackground
at android.support.v4.app.JobIntentService$CommandProcessor.doInBackground
at android.os.AsyncTask$2.call(AsyncTask.java:292)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
at java.lang.Thread.run(Thread.java:818)

**Comment by tatanka987** [comment]
try adding 
compile "com.google.firebase:firebase-core:**11.6.2**"
compile "com.google.android.gms:play-services-gcm:**11.6.2**"

it is needed in order for using all libs with same version in your project (version of this libs in our SDK is 11.4.2 but all libs in your project must be same version)

**Comment by ominfowave** [comment]
Thanks @tatanka987 it's working.
