### ISSUE TITLE
at com.quickblox.core.helper.CommonUtils.notifyEntityCallbackOnSuccess(Unknown Source)

### ISSUE THREAD

**Issue by A2DNEW** [QuickBlox/quickblox-android-sdk#514]
MediaStreamManager return null !

Error line : QBRTCVideoTrack localVideoTrack = session.getMediaStreamManager().getLocalVideoTrack();
Log : 
```
at com.quickblox.core.helper.CommonUtils.notifyEntityCallbackOnSuccess(Unknown Source)
at com.quickblox.chat.QBChatService$4.run(Unknown Source)
at android.os.Handler.handleCallback(Handler.java:730)
at android.os.Handler.dispatchMessage(Handler.java:92)
```

```
QBRTCSession session = QBRTCClient.getInstance(G.currentActivity).createNewSessionWithOpponents(opponents,qbConferenceType);
        Log.i("errorCheck", "QR1: " + session);
                        session.startCall(userInfo);
                        /* START */
                        //QBRTCVideoTrack videoTrack = null;

                        QBRTCSignalingCallback signalingCallback = new QBRTCSignalingCallback(){
                            public void onSuccessSendingPacket(QBSignalingSpec.QBSignalCMD packetType, Integer opponentId){
                                Log.i("errorCheck", "ppp1: " + opponentId);
                            }
                            public void onErrorSendingPacket(QBSignalingSpec.QBSignalCMD packetType, Integer opponentId,
                                                             QBRTCSignalException e){
                                Log.i("errorCheck", "ppp2: " + e);
                            }
                        };

                        session.addSignalingCallback(signalingCallback);
                        session.removeSignalingCallback(signalingCallback);

                        QBRTCVideoTrack localVideoTrack = session.getMediaStreamManager().getLocalVideoTrack();
                        localVideoTrack.setEnabled(true);
```
Hi
How i can solve this problem ?

**Comment by RomanPronin** [comment]
Hi, MediaStreamManager is null because of your Local media Stream is not inited yet. So, you don't have localVideoTrack yet. Look at [sample-videochat](https://github.com/QuickBlox/quickblox-android-sdk/tree/master/sample-videochat-webrtc) for correct implementation.

**Comment by A2DNEW** [comment]
Thx, i see sample videochat but i dont undrestand
Can you help me more on my code ?

**Comment by RomanPronin** [comment]
For example, you can get LocalVideoTrack in onLocalVideoTrackReceive method of QBRTCClientVideoTracksCallbacks and get it after by getMediaStreamManager.

**Comment by A2DNEW** [comment]
Thank you
But i am beginner
Can you type code or java file ?

**Comment by RomanPronin** [comment]
@A2DNEW, In sample video chat class [VideoConversationFragment](https://github.com/QuickBlox/quickblox-android-sdk/blob/master/sample-videochat-webrtc/src/main/java/com/quickblox/sample/groupchatwebrtc/fragments/VideoConversationFragment.java) implements QBRTCClientVideoTracksCallbacks, here is part of that code:
`    @Override`
 `   public void onLocalVideoTrackReceive(QBRTCSession qbrtcSession, final QBRTCVideoTrack videoTrack) {`
&nbsp;&nbsp;&nbsp;`        localVideoTrack = videoTrack;`
&nbsp;&nbsp;`...`
&nbsp;&nbsp;&nbsp;`        }`
`    }`
So, just explore more deeply this sample, it's the best way to understand video chat implementation logic.

**Comment by A2DNEW** [comment]
Thank you
I change class to:
`public class VideoActivity extends E implements QBRTCClientSessionCallbacks,QBRTCClientVideoTracksCallbacks {`
And add:
```
@Override
    public void onLocalVideoTrackReceive(QBRTCSession qbrtcSession, QBRTCVideoTrack qbrtcVideoTrack) {
        Log.i("errorCheck", "WW1: " + qbrtcSession);
        qbrtcVideoTrack.addRenderer(new VideoRenderer(surfaceView));
        surfaceView.setMirror(true);
        surfaceView.requestLayout();
    }
```
But not set log
How i run `onLocalVideoTrackReceive` ?

**Comment by RomanPronin** [comment]
You should add QBRTCClientVideoTracksCallbacks, in your case in VideoActivity add:
`currentSession.addVideoTrackCallbacksListener(this);`

**Comment by RomanPronin** [comment]
Yeah, my advice, just take sample video chat, and modify it as you need. This is the simplest way.

**Comment by A2DNEW** [comment]
Thank you for comment
I do not use sample videochat-webrtc
I paste code here
Please tell me correct or not ?
This codes calling correct but not incoming receive!

VideoActivity.java
```
import android.media.MediaPlayer;
import android.os.Bundle;
import android.os.Handler;
import android.util.Log;
import android.view.View;
import android.widget.FrameLayout;
import android.widget.ImageView;
import android.widget.TextView;
import android.widget.Toast;

import com.quickblox.chat.QBChatService;
import com.quickblox.chat.QBSignaling;
import com.quickblox.chat.QBWebRTCSignaling;
import com.quickblox.chat.listeners.QBVideoChatSignalingManagerListener;
import com.quickblox.core.QBEntityCallback;
import com.quickblox.core.exception.QBResponseException;
import com.quickblox.videochat.webrtc.QBMediaStreamManager;
import com.quickblox.videochat.webrtc.QBRTCCameraVideoCapturer;
import com.quickblox.videochat.webrtc.QBRTCClient;
import com.quickblox.videochat.webrtc.QBRTCConfig;
import com.quickblox.videochat.webrtc.QBRTCSession;
import com.quickblox.videochat.webrtc.QBRTCTypes;
import com.quickblox.videochat.webrtc.callbacks.QBRTCClientSessionCallbacks;
import com.quickblox.videochat.webrtc.callbacks.QBRTCClientVideoTracksCallbacks;
import com.quickblox.videochat.webrtc.view.QBRTCSurfaceView;
import com.quickblox.videochat.webrtc.view.QBRTCVideoTrack;

import org.webrtc.VideoRenderer;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class VideoActivity extends E implements QBRTCClientSessionCallbacks,QBRTCClientVideoTracksCallbacks {

    private int userid;
    private Boolean isOutgoing,micE=true,vidE=true;
    private QBRTCSurfaceView surfaceView,remoteview;
    private MediaPlayer mp;
    private QBRTCSession currentsession;
    private QBMediaStreamManager mediaStreamManager;
    private ImageView mic,video;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.video);
        userid=getIntent().getIntExtra("user",1);
        userid = 111;
        isOutgoing=getIntent().getBooleanExtra("isoutgoing",false);
        isOutgoing = true;
        ProcessCalls();
        InitSignalling();
        if (isOutgoing) {
            //CallUser();
            SetCallerName(userid);
        }
        Log.i("errorCheck", "Nz: " + userid);
        Log.i("errorCheck", "Na: " + isOutgoing);
        if(getIntent().getBooleanExtra("service",false)){
            Log.i("errorCheck", "x");
            /*SetLayoutForReceiveCall(DataHolder.getInstance().getSession(),DataHolder.getInstance().getUserInfo());
            SetCallerName(DataHolder.getInstance().getSession().getCallerID());
            Uri notification = RingtoneManager.getDefaultUri(RingtoneManager.TYPE_RINGTONE);
            mp = MediaPlayer.create(getApplicationContext(), notification);
            mp.start();*/
        }


        mic=(ImageView)findViewById(R.id.mic);
        mic.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                if(micE){
                    micE=false;
                    AudioManage();
                }else {
                    micE=true;
                    AudioManage();
                }
            }
        });
        video=(ImageView)findViewById(R.id.video);
        video.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                if(vidE){
                    vidE=false;
                    VideoManage();
                }else {
                    vidE=true;
                    VideoManage();
                }
            }
        });

        surfaceView =(QBRTCSurfaceView)findViewById(R.id.localView);
        surfaceView.setMirror(true);
        surfaceView.requestLayout();

        remoteview=(QBRTCSurfaceView)findViewById(R.id.opponentView);
        remoteview.requestLayout();

        QBRTCClient.getInstance(this).addSessionCallbacksListener(this);
    }

    private void SetCallerName(Integer callerID) {
        TextView callerName=(TextView)findViewById(R.id.callername);
        TextView callertime=(TextView)findViewById(R.id.callTime);
        callerName.setText(callerID+" , You:");
        if(isOutgoing){
            callertime.setText("Calling...");
        }

    }

    private void InitSignalling() {
        final QBChatService chatService = QBChatService.getInstance();

        /*QBUsers.signIn(G.userQB).performAsync(new QBEntityCallback<QBUser>() {
            @Override
            public void onSuccess(QBUser qUser, Bundle args) {
                Log.i("errorCheck", "Y1: " + qUser.getId());

                G.userQB.setId(qUser.getId());*/
                Log.i("errorCheck", "ERR1: " + G.userQB);
                chatService.login(G.userQB, new QBEntityCallback() {
                    @Override
                    public void onSuccess(Object result, Bundle params) {
                        Log.i("errorCheck", "R0: " + result);
                        Log.i("errorCheck", "R1: " + params);

                        chatService.getVideoChatWebRTCSignalingManager().addSignalingManagerListener(new QBVideoChatSignalingManagerListener() {
                            @Override
                            public void signalingCreated(QBSignaling qbSignaling, boolean createdLocally) {
                                Log.i("errorCheck", "Q1: " + qbSignaling);
                                Log.i("errorCheck", "Q2: " + createdLocally);
                                if (!createdLocally) {
                                    QBRTCClient.getInstance(VideoActivity.this).addSignaling((QBWebRTCSignaling) qbSignaling);
                                }
                            }
                        });

                        CallUser();
                    }

                    @Override
                    public void onError(QBResponseException errors) {
                        Log.i("errorCheck", "E1: " + errors);
                    }
                });
            /*}

            @Override
            public void onError(QBResponseException error) {
                Log.i("errorCheck", "N1: " + error);
            }
        });*/

    }

    private void ProcessCalls() {
        QBRTCClient.getInstance(this).prepareToProcessCalls();
    }

    private void CallUser() {
        List<Integer> opponents = new ArrayList<Integer>();
        opponents.add(userid);

        Map<String, String> userInfo = new HashMap<>();
        userInfo.put("key", "value");

        QBRTCConfig.setDebugEnabled(true);
        QBRTCClient.getInstance(getApplicationContext()).prepareToProcessCalls();
        QBRTCTypes.QBConferenceType qbConferenceType = QBRTCTypes.QBConferenceType.QB_CONFERENCE_TYPE_VIDEO;
        QBRTCClient.getInstance(getApplicationContext()).prepareToProcessCalls();

        QBRTCSession session = QBRTCClient.getInstance(G.currentActivity).createNewSessionWithOpponents(opponents, qbConferenceType);

        session.addVideoTrackCallbacksListener(this);

        session.startCall(userInfo);
        Log.i("errorCheck", "QR1: " + session);
        SetCallButtonsDialing(session,userInfo);
        StartDialRinging();
    }

    private void SetCallButtonsDialing(final QBRTCSession session, final Map<String, String> userInfo) {
        FrameLayout call=(FrameLayout)findViewById(R.id.CallerLayout);
        call.setVisibility(View.VISIBLE);
        findViewById(R.id.Endcall).setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                session.hangUp(userInfo);
                VideoActivity.this.finish();
            }
        });
    }

    public void AudioManage(){
        if(mediaStreamManager!=null) {
            if (mediaStreamManager.isAudioEnabled()) {
                mediaStreamManager.setAudioEnabled(false);
                mic.setImageResource(R.drawable.ic_mic_off_black_24dp);
            } else {
                mediaStreamManager.setAudioEnabled(true);
                mic.setImageResource(R.drawable.ic_mic_black_24dp);
            }
        }
    }

    public void VideoManage(){
        if(mediaStreamManager!=null) {
            if (mediaStreamManager.isVideoEnabled()) {
                mediaStreamManager.setVideoEnabled(false);
                video.setImageResource(R.drawable.ic_videocam_off_black_24dp);
            } else {
                mediaStreamManager.setVideoEnabled(true);
                video.setImageResource(R.drawable.ic_videocam_black_24dp);
            }
        }
    }


    @Override
    public void onReceiveNewSession(QBRTCSession qbrtcSession) {
        Log.i("errorCheck","x");

        qbrtcSession.addVideoTrackCallbacksListener(this);
        Map<String,String> userInfo = qbrtcSession.getUserInfo();
        SetLayoutForReceiveCall(qbrtcSession,userInfo);
    }

    private void SetLayoutForReceiveCall(final QBRTCSession qbrtcSession,final Map<String, String> userInfo) {
        final FrameLayout receive=(FrameLayout)findViewById(R.id.answerlayout);
        receive.setVisibility(View.VISIBLE);
        qbrtcSession.addVideoTrackCallbacksListener(this);
        final ImageView calll=(ImageView)findViewById(R.id.answerCall);
        calll.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                // Accept incoming call
                qbrtcSession.acceptCall(userInfo);
                receive.setVisibility(View.GONE);
                SetCallButtonsDialing(qbrtcSession,userInfo);
                StartTimer();
                if(mp!=null&&mp.isPlaying())
                {
                    mp.stop();
                }
            }
        });

        findViewById(R.id.rejectcall).setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                qbrtcSession.rejectCall(userInfo);
                VideoActivity.this.finish();
                if(mp!=null&&mp.isPlaying())
                {
                    mp.stop();
                }
            }
        });
    }

    private void StartTimer() {
        final TextView timer=(TextView)findViewById(R.id.callTime);
        timer.setText("00:00");
        final Handler handler = new Handler();
        Runnable runnable = new Runnable() {
            private long startTime = System.currentTimeMillis();
            public void run() {
                while (true) {
                    try {
                        Thread.sleep(1000);
                    }
                    catch (InterruptedException e) {
                        e.printStackTrace();
                    }
                    handler.post(new Runnable(){
                        public void run() {

                            int millis=(int)(System.currentTimeMillis() - startTime)/1000;
                            int min=millis/60;
                            int sec=millis%60;
                            timer.setText((min<10?"0"+min:min)+":"+(sec<10?"0"+sec:sec));
                        }
                    });
                }
            }
        };
        new Thread(runnable).start();
    }

    @Override
    public void onUserNoActions(QBRTCSession qbrtcSession, Integer integer) {

        Toast.makeText(this, "no action by user", Toast.LENGTH_SHORT).show();
        if(mp!=null&&mp.isPlaying())
        {
            mp.stop();
        }
    }

    @Override
    public void onSessionStartClose(QBRTCSession qbrtcSession) {
        qbrtcSession.addVideoTrackCallbacksListener(this);
        try {
            qbrtcSession.getMediaStreamManager().setVideoCapturer(new QBRTCCameraVideoCapturer(this, null));
            mediaStreamManager = qbrtcSession.getMediaStreamManager();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    @Override
    public void onUserNotAnswer(QBRTCSession qbrtcSession, Integer integer) {

        Toast.makeText(this, "No answer", Toast.LENGTH_SHORT).show();
        if(mp!=null&&mp.isPlaying())
        {
            mp.stop();
        }
        finish();
    }

    @Override
    public void onCallRejectByUser(QBRTCSession qbrtcSession, Integer integer, Map<String, String> map) {
        Toast.makeText(this, "Call rejected", Toast.LENGTH_SHORT).show();
        if(mp!=null&&mp.isPlaying())
        {
            mp.stop();
        }
        finish();
    }

    @Override
    public void onCallAcceptByUser(QBRTCSession qbrtcSession, Integer integer, Map<String, String> map) {
        qbrtcSession.addVideoTrackCallbacksListener(this);
        if(mp!=null&&mp.isPlaying())
        {
            mp.stop();
        }
        StartTimer();
    }

    @Override
    public void onReceiveHangUpFromUser(QBRTCSession qbrtcSession, Integer integer, Map<String, String> map) {
        if(mp!=null&&mp.isPlaying())
        {
            mp.stop();
        }
        Toast.makeText(this, "Call ended by user", Toast.LENGTH_SHORT).show();
        finish();
    }

    @Override
    public void onSessionClosed(QBRTCSession qbrtcSession) {
        if(mp!=null&&mp.isPlaying())
        {
            mp.stop();
        }
    }

    @Override
    public void onLocalVideoTrackReceive(QBRTCSession qbrtcSession, QBRTCVideoTrack qbrtcVideoTrack) {
        Log.i("errorCheck", "WW1: " + qbrtcSession);
        qbrtcVideoTrack.addRenderer(new VideoRenderer(surfaceView));
        surfaceView.setMirror(true);
        surfaceView.requestLayout();
    }

    @Override
    public void onRemoteVideoTrackReceive(QBRTCSession qbrtcSession, QBRTCVideoTrack qbrtcVideoTrack, Integer integer) {
        Log.i("errorCheck", "WW2: " + qbrtcSession);

        qbrtcVideoTrack.addRenderer(new VideoRenderer(remoteview));
        mediaStreamManager = qbrtcSession.getMediaStreamManager();
        remoteview.requestLayout();
    }

    public void StartDialRinging(){
        try {
            mp = MediaPlayer.create(getApplicationContext(), R.raw.beep);
            mp.setLooping(true);
            mp.start();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
```

Manifest.xml
```
<service
            android:name=".MyFirebaseMessagingService">
            <intent-filter>
                <action android:name="com.google.firebase.MESSAGING_EVENT"/>
            </intent-filter>
        </service>
        <service
            android:name=".MyFirebaseInstanceIDService">
            <intent-filter>
                <action android:name="com.google.firebase.INSTANCE_ID_EVENT"/>
            </intent-filter>
        </service>

        <service android:name=".CallService" />

        <receiver
            android:name="com.google.android.gms.gcm.GcmReceiver"
            android:exported="true"
            android:permission="com.google.android.c2dm.permission.SEND">
            <intent-filter>
                <action android:name="com.google.android.c2dm.intent.RECEIVE" />
                <action android:name="com.google.android.c2dm.intent.REGISTRATION" />

                <category android:name="com.quickblox.sample.groupchatwebrtc" />
            </intent-filter>
        </receiver>

        <service
            android:name=".GcmPushListenerService"
            android:exported="false">
            <intent-filter>
                <action android:name="com.google.android.c2dm.intent.RECEIVE" />
            </intent-filter>
        </service>

        <!--<service
            android:name=".GcmPushListenerService"
            android:exported="false">
            <intent-filter>
                <action android:name="com.google.android.gms.iid.InstanceID" />
            </intent-filter>
        </service>-->

        <meta-data android:name="com.quickblox.messages.TYPE" android:value="GCM" />
        <meta-data android:name="com.quickblox.messages.SENDER_ID" android:value="1" />
        <meta-data android:name="com.quickblox.messages.QB_ENVIRONMENT" android:value="DEVELOPMENT" />
```

GcmPushListenerService.java
```
public class GcmPushListenerService extends GcmListenerService {
    private static final String TAG = GcmPushListenerService.class.getSimpleName();

    @Override
    public void onMessageReceived(String from, Bundle data) {
        //String message = data.getString(GcmConsts.EXTRA_GCM_MESSAGE);
        Log.i(TAG, "From: " + from);
        Log.i(TAG, "Message: " + data);

        /*SharedPrefsHelper sharedPrefsHelper = SharedPrefsHelper.getInstance();
        if (sharedPrefsHelper.hasQbUser()) {
            Log.d(TAG, "App have logined user");
            QBUser qbUser = sharedPrefsHelper.getQbUser();
            startLoginService(qbUser);
        }*/
    }

    private void startLoginService(QBUser qbUser){
        //allService.start(this, qbUser);
    }
}
```

Callservice.java
```
public class CallService extends Service {
    private static final String TAG = CallService.class.getSimpleName();
    private QBChatService chatService;
    private QBRTCClient rtcClient;
    private PendingIntent pendingIntent;
    private int currentCommand;
    private QBUser currentUser;

    public static void start(Context context, QBUser qbUser, PendingIntent pendingIntent) {
        Intent intent = new Intent(context, CallService.class);

        /*intent.putExtra(Consts.EXTRA_COMMAND_TO_SERVICE, Consts.COMMAND_LOGIN);
        intent.putExtra(Consts.EXTRA_QB_USER, qbUser);
        intent.putExtra(Consts.EXTRA_PENDING_INTENT, pendingIntent);*/

        context.startService(intent);
    }

    public static void start(Context context, QBUser qbUser) {
        start(context, qbUser, null);
    }

    @Override
    public void onCreate() {
        super.onCreate();

        createChatService();

        Log.d(TAG, "Service onCreate()");
    }

    @Override
    public int onStartCommand(Intent intent, int flags, int startId) {
        Log.d(TAG, "Service started");

        parseIntentExtras(intent);

        startSuitableActions();

        return START_REDELIVER_INTENT;
    }

    private void parseIntentExtras(Intent intent) {
        if (intent != null && intent.getExtras() != null) {
            /*currentCommand = intent.getIntExtra(Consts.EXTRA_COMMAND_TO_SERVICE, Consts.COMMAND_NOT_FOUND);
            pendingIntent = intent.getParcelableExtra(Consts.EXTRA_PENDING_INTENT);
            currentUser = (QBUser) intent.getSerializableExtra(Consts.EXTRA_QB_USER);*/
        }
    }

    private void startSuitableActions() {
        /*if (currentCommand == Consts.COMMAND_LOGIN) {
            startLoginToChat();
        } else if (currentCommand == Consts.COMMAND_LOGOUT) {
            logout();
        }*/
    }

    private void createChatService() {
        if (chatService == null) {
            QBChatService.setDebugEnabled(true);
            chatService = QBChatService.getInstance();
        }
    }

    private void startLoginToChat() {
        if (!chatService.isLoggedIn()) {
            loginToChat(currentUser);
        } else {
            sendResultToActivity(true, null);
        }
    }

    private void loginToChat(QBUser qbUser) {
        chatService.login(qbUser, new QBEntityCallback<QBUser>() {
            @Override
            public void onSuccess(QBUser qbUser, Bundle bundle) {
                Log.d(TAG, "login onSuccess");
                startActionsOnSuccessLogin();
            }

            @Override
            public void onError(QBResponseException e) {
                Log.d(TAG, "login onError " + e.getMessage());
                sendResultToActivity(false, e.getMessage() != null
                        ? e.getMessage()
                        : "Login error");
            }
        });
    }

    private void startActionsOnSuccessLogin() {
        initPingListener();
        initQBRTCClient();
        sendResultToActivity(true, null);
    }

    private void initPingListener() {
        /*ChatPingAlarmManager.onCreate(this);
        ChatPingAlarmManager.getInstanceFor().addPingListener(new PingFailedListener() {
            @Override
            public void pingFailed() {
                Log.d(TAG, "Ping chat server failed");
            }
        });*/
    }

    private void initQBRTCClient() {
        rtcClient = QBRTCClient.getInstance(getApplicationContext());
        // Add signalling manager
        chatService.getVideoChatWebRTCSignalingManager().addSignalingManagerListener(new QBVideoChatSignalingManagerListener() {
            @Override
            public void signalingCreated(QBSignaling qbSignaling, boolean createdLocally) {
                if (!createdLocally) {
                    rtcClient.addSignaling((QBWebRTCSignaling) qbSignaling);
                }
            }
        });

        // Configure
        QBRTCConfig.setDebugEnabled(true);
        //SettingsUtil.configRTCTimers(CallService.this);

        // Add service as callback to RTCClient
        //rtcClient.addSessionCallbacksListener(WebRtcSessionManager.getInstance(this));
        rtcClient.prepareToProcessCalls();
    }

    private void sendResultToActivity(boolean isSuccess, String errorMessage) {
        if (pendingIntent != null) {
            Log.d(TAG, "sendResultToActivity()");
            /*try {
                /*Intent intent = new Intent();
                intent.putExtra(Consts.EXTRA_LOGIN_RESULT, isSuccess);
                intent.putExtra(Consts.EXTRA_LOGIN_ERROR_MESSAGE, errorMessage);

                //pendingIntent.send(CallService.this, Consts.EXTRA_LOGIN_RESULT_CODE, intent);
            } catch (PendingIntent.CanceledException e) {
                String errorMessageSendingResult = e.getMessage();
                Log.d(TAG, errorMessageSendingResult != null
                        ? errorMessageSendingResult
                        : "Error sending result to activity");
            }*/
        }
    }

    public static void logout(Context context) {
        Intent intent = new Intent(context, CallService.class);
        //intent.putExtra(Consts.EXTRA_COMMAND_TO_SERVICE, Consts.COMMAND_LOGOUT);
        context.startService(intent);
    }

    private void logout() {
        destroyRtcClientAndChat();
    }

    private void destroyRtcClientAndChat() {
        if (rtcClient != null) {
            rtcClient.destroy();
        }
        //ChatPingAlarmManager.onDestroy();
        if (chatService != null) {
            chatService.logout(new QBEntityCallback<Void>() {
                @Override
                public void onSuccess(Void aVoid, Bundle bundle) {
                    chatService.destroy();
                }

                @Override
                public void onError(QBResponseException e) {
                    Log.d(TAG, "logout onError " + e.getMessage());
                    chatService.destroy();
                }
            });
        }
        stopSelf();
    }

    @Override
    public void onDestroy() {
        Log.d(TAG, "Service onDestroy()");
        super.onDestroy();
    }

    @Nullable
    @Override
    public IBinder onBind(Intent intent) {
        Log.d(TAG, "Service onBind)");
        return null;
    }

    @Override
    public void onTaskRemoved(Intent rootIntent) {
        Log.d(TAG, "Service onTaskRemoved()");
        super.onTaskRemoved(rootIntent);
        destroyRtcClientAndChat();
    }
}

```

Please help me
Where are my code is wrong ?!
Please :(

**Comment by A2DNEW** [comment]
@RomanPronin can help me this topic ? https://github.com/QuickBlox/quickblox-android-sdk/issues/515

**Comment by QB-nikolay-zolotarov** [comment]
Hello QuickBlox customer,

This is Nikolay from QuickBlox support.

The issue was closed as it is outdated.

Please check the relevant section of our documentation here:
[https://docs.quickblox.com/docs/android-video-calling](https://docs.quickblox.com/docs/android-video-calling)

Also, please update the SDK to the latest version:
[https://github.com/QuickBlox/quickblox-android-sdk-releases/releases/tag/3.9.11](https://github.com/QuickBlox/quickblox-android-sdk-releases/releases/tag/3.9.11)

Additionally, please check our new samples:
[https://docs.quickblox.com/docs/code-samples#video-calling-samples](https://docs.quickblox.com/docs/code-samples#video-calling-samples)

If it is still relevant after reviewing the updated information, feel free to open a new issue.

Have a nice day.
