### ISSUE TITLE
while Integrate QuickBlox Sdk Crash Application

### ISSUE THREAD

**Issue by bhaveshintorque** [QuickBlox/quickblox-android-sdk#526]
*Help avoid duplicate issue reports, check [existing issues](link to issues section of repo)*
==> java.lang.NoClassDefFoundError: Failed resolution of: Lcom/quickblox/messages/services/SubscribeService;
                                                                        at com.quickblox.messages.QBPushNotifications$1.onSessionRestored(Unknown Source)
                                                                        at com.quickblox.auth.session.QBSessionManager$4.run(Unknown Source)
                                                                        at android.os.Handler.handleCallback(Handler.java:751)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                        at android.os.Looper.loop(Looper.java:154)
                                                                        at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
                                                                     Caused by: java.lang.ClassNotFoundException: com.quickblox.messages.services.SubscribeService
                                                                        at java.lang.VMClassLoader.findLoadedClass(Native Method)
                                                                        at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:742)
                                                                        at java.lang.ClassLoader.loadClass(ClassLoader.java:362)
                                                                        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                                        at com.quickblox.messages.QBPushNotifications$1.onSessionRestored(Unknown Source) 
                                                                        at com.quickblox.auth.session.QBSessionManager$4.run(Unknown Source) 
                                                                        at android.os.Handler.handleCallback(Handler.java:751) 
                                                                        at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                        at android.os.Looper.loop(Looper.java:154) 
                                                                        at android.app.ActivityThread.main(ActivityThread.java:6119) 
                                                                       

**Environment details**
*(Operating system, browser information, SDK version)*
==> sdk version 27

**Did this work before?**
==> in Demo its working fine but when i try to implement my demo yo my code it crashed while login.

**Logs**
*(please, use github [gist](https://gist.github.com/))*
==> java.lang.NoClassDefFoundError: Failed resolution of: Lcom/quickblox/messages/services/SubscribeService;
                                                                        at com.quickblox.messages.QBPushNotifications$1.onSessionRestored(Unknown Source)
                                                                        at com.quickblox.auth.session.QBSessionManager$4.run(Unknown Source)
                                                                        at android.os.Handler.handleCallback(Handler.java:751)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                        at android.os.Looper.loop(Looper.java:154)
                                                                        at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
                                                                     Caused by: java.lang.ClassNotFoundException: com.quickblox.messages.services.SubscribeService
                                                                        at java.lang.VMClassLoader.findLoadedClass(Native Method)
                                                                        at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:742)
                                                                        at java.lang.ClassLoader.loadClass(ClassLoader.java:362)
                                                                        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                                        at com.quickblox.messages.QBPushNotifications$1.onSessionRestored(Unknown Source) 
                                                                        at com.quickblox.auth.session.QBSessionManager$4.run(Unknown Source) 
                                                                        at android.os.Handler.handleCallback(Handler.java:751) 
                                                                        at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                        at android.os.Looper.loop(Looper.java:154) 
                                                                        at android.app.ActivityThread.main(ActivityThread.java:6119) 

**Steps to reproduce the behavior**

**Any others comments?**

**Comment by RomanPronin** [comment]
Hi, @bhaveshintorque,  if you use ProGuard, try to add next line
-keep class com.quickblox.messages.services.SubscribeService { *; } for excluding this class from obfuscation.

**Comment by bhaveshintorque** [comment]
Hi Roman, I have tired it but its not working. Can you please provide me another solution?

**Comment by RomanPronin** [comment]
Well, with disabled proguard does it work?

**Comment by bhaveshintorque** [comment]
@RomanPronin i also try using disable pro guard but still it's not work. any other solution?

**Comment by RomanPronin** [comment]
Try to change android sdk version to 26 like in the samples.

**Comment by bhaveshintorque** [comment]
@RomanPronin  i have also try using sdk version 26 but it's also not work

**Comment by RomanPronin** [comment]
So, if in samples it's all ok, the problem is in your project, maybe you are using different quickblox sdk versions in modules, try to find out comparing with samples.

**Comment by bhaveshintorque** [comment]
@RomanPronin  thanks for help..

**Comment by QB-nikolay-zolotarov** [comment]
Hello QuickBlox customer,

This is Nikolay from QuickBlox support.

The issue was closed as it was outdated.

Please update the SDK to the latest version:
[https://github.com/QuickBlox/quickblox-ios-sdk/releases/tag/2.17.10](https://github.com/QuickBlox/quickblox-ios-sdk/releases/tag/2.17.10)

Additionally, please check our new samples:
[https://docs.quickblox.com/docs/code-samples#chat-samples](https://docs.quickblox.com/docs/code-samples#chat-samples)

If it is still relevant after reviewing the updated information, feel free to open a new issue.

Have a nice day.
