### ISSUE TITLE
3.6.0 Crashes - com.quickblox.messages.services.SubscribeService

### ISSUE THREAD

**Issue by Semafu** [QuickBlox/quickblox-android-sdk#531]
I am using 3.6.0, my app crashes as follows:

java.lang.NoClassDefFoundError: com.quickblox.messages.services.SubscribeService at com.quickblox.messages.QBPushNotifications$1.onSessionCreated()

Full dump:
02-01 11:17:49.496 3989-3989/com.prographo.cduk E/AndroidRuntime: FATAL EXCEPTION: main
                                                                  Process: xxx.xxx.xxx, PID: 3989
                                                                  java.lang.NoClassDefFoundError: com.quickblox.messages.services.SubscribeService
                                                                      at com.quickblox.messages.QBPushNotifications$1.onSessionCreated(Unknown Source)
                                                                      at com.quickblox.auth.session.QBSessionManager$1.run(Unknown Source)
                                                                      at android.os.Handler.handleCallback(Handler.java:739)
                                                                      at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                      at android.os.Looper.loop(Looper.java:135)
                                                                      at android.app.ActivityThread.main(ActivityThread.java:5343)
                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                      at java.lang.reflect.Method.invoke(Method.java:372)
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)
02-01 11:17:49.501 883-1685/? W/ActivityManager:   Force finishing activity 1 xxx.xxx.xxx/.MainActivity

OS: Android - XT1039 (Android 5.1, API 22)

What does it mean?
Is there new listeners I have to define?

**Comment by Semafu** [comment]
Moving to 3.3.4 prevents crashing.

**Comment by RomanPronin** [comment]
Hi, @Semafu, look at #526

**Comment by Semafu** [comment]
Does not crash with 3.3.4 - does that not mean a bug was introduced in 3.6.0?

**Comment by RomanPronin** [comment]
I don't think so. Just set 3.6.0 version in all Quickblox library modules you have. Maybe clean project, and clean gradle cache if need.

**Comment by Semafu** [comment]
deleted ~/.gradle and the .gradle in the project directory.
invalidated all caches & restarted
did a Clean Build

-> still crashes with same error.

I think I will just try with 3.3.4

**Comment by RomanPronin** [comment]
@Semafu, sure you can use 3.3.4, but if you want, you can always take a look at the [samples](https://github.com/QuickBlox/quickblox-android-sdk) with this 3.6.0 version.

**Comment by Semafu** [comment]
That's a big project, all I want is chat + push. I will give it a go.

**Comment by Semafu** [comment]
I settle with 3.3.0

**Comment by Nikhil-z** [comment]
This issue is still happening with latest 3.8.1 version of SDK. Any viable fix available?
