### ISSUE TITLE
NullPointerException: Attempt to invoke virtual method 'com.quickblox.users.model.QBUser com.quickblox.chat.QBChatService.getUser()' on a null object reference

### ISSUE THREAD

**Issue by Shahjahan786** [QuickBlox/quickblox-android-sdk#544]
**Sometimes when my application is in idle chat session is dropped and at that time I get this error
I don't want my session to be dropped.**

my settings are below:

```
QBSettings.getInstance().setLogLevel(LogLevel.DEBUG);
            QBChatService.setDebugEnabled(true);

            QBChatService.ConfigurationBuilder chatServiceConfigurationBuilder = new QBChatService.ConfigurationBuilder();
            chatServiceConfigurationBuilder.setSocketTimeout(0); //Sets chat socket's read timeout in seconds
            chatServiceConfigurationBuilder.setKeepAlive(true); //Sets connection socket's keepAlive option.
            chatServiceConfigurationBuilder.setUseTls(true); //Sets the TLS security mode used when making the connection. By default TLS is disabled.

            QBChatService.setConfigurationBuilder(chatServiceConfigurationBuilder);
            QBChatService.setDefaultPacketReplyTimeout(120 * 1000);
            QBChatService.setDefaultConnectionTimeout(120 * 1000);
            //QBChatService.setDefaultAutoSendPresenceInterval(5);

            QBHttpConnectionConfig.setConnectTimeout(120 * 1000);
            QBHttpConnectionConfig.setReadTimeout(120 * 1000);
```

```
02-14 15:26:15.379 14071-14071/com.nayapay.app E/AndroidRuntime: FATAL EXCEPTION: main
                                                                 Process: com.app, PID: 14071
                                                                 java.lang.NullPointerException: Attempt to invoke virtual method 'com.quickblox.users.model.QBUser com.quickblox.chat.QBChatService.getUser()' on a null object reference
                                                                     at com.quickblox.chat.model.QBChatDialog.getRecipientId(Unknown Source)
                                                                     at com.app.db.models.Dialog.convert(Dialog.java:199)
                                                                     at com.nayapay.app.chat.utils.DialogsManager.showNewMessageNotification(DialogsManager.java:170)
                                                                     at com.app.chat.utils.DialogsManager.showNotification(DialogsManager.java:141)
                                                                     at com.app.chat.utils.DialogsManager.onGlobalMessageReceived(DialogsManager.java:104)
                                                                     at com.app.chat.ui.fragments.ChatDialogListFragment$AllDialogsMessageListener.processMessage(ChatDialogListFragment.java:754)
                                                                     at com.quickblox.chat.QBIncomingMessagesManager$2.run(Unknown Source)
                                                                     at android.os.Handler.handleCallback(Handler.java:751)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                     at android.os.Looper.loop(Looper.java:154)
                                                                     at android.app.ActivityThread.main(ActivityThread.java:6642)
                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
```

**Comment by Shahjahan786** [comment]
**Also I get this message when sending message after remaining idle for some time**

```
02-14 12:52:30.241 24015-24015/com.app W/System.err: org.jivesoftware.smack.SmackException$NotConnectedException: Client is not, or no longer, connected.
02-14 12:52:30.248 24015-24015/com.app W/System.err:     at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketWriter.throwNotConnectedExceptionIfDoneAndResumptionNotPossible(Unknown Source:16)
02-14 12:52:30.248 24015-24015/com.app W/System.err:     at org.jivesoftware.smack.tcp.XMPPTCPConnection.throwNotConnectedExceptionIfAppropriate(Unknown Source:12)
02-14 12:52:30.248 24015-24015/com.app W/System.err:     at org.jivesoftware.smack.AbstractXMPPConnection.sendStanza(Unknown Source:6)
02-14 12:52:30.248 24015-24015/com.app W/System.err:     at com.quickblox.chat.QBMessageStatusesSender.sendChatState(Unknown Source:4)
02-14 12:52:30.248 24015-24015/com.app W/System.err:     at com.quickblox.chat.QBGroupChatManager.a(Unknown Source:6)
02-14 12:52:30.248 24015-24015/com.app W/System.err:     at com.quickblox.chat.QBGroupChat.sendIsTypingNotification(Unknown Source:8)
02-14 12:52:30.248 24015-24015/com.app W/System.err:     at com.quickblox.chat.model.QBChatDialog.sendIsTypingNotification(Unknown Source:5)
02-14 12:52:30.248 24015-24015/com.app W/System.err:     at com.app.chat.ui.activity.ChatMessagesActivity$6.onTextChanged(ChatMessagesActivity.java:544)
02-14 12:52:30.248 24015-24015/com.app W/System.err:     at android.widget.TextView.sendOnTextChanged(TextView.java:9364)
02-14 12:52:30.248 24015-24015/com.app W/System.err:     at android.widget.TextView.handleTextChanged(TextView.java:9451)
02-14 12:52:30.249 24015-24015/com.app W/System.err:     at android.widget.TextView$ChangeWatcher.onTextChanged(TextView.java:11926)
02-14 12:52:30.249 24015-24015/com.app W/System.err:     at android.text.SpannableStringBuilder.sendTextChanged(SpannableStringBuilder.java:1252)
02-14 12:52:30.249 24015-24015/com.app W/System.err:     at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:573)
02-14 12:52:30.249 24015-24015/com.app W/System.err:     at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:504)
02-14 12:52:30.249 24015-24015/com.app W/System.err:     at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:502)
02-14 12:52:30.249 24015-24015/com.app W/System.err:     at android.view.inputmethod.BaseInputConnection.replaceText(BaseInputConnection.java:843)
02-14 12:52:30.249 24015-24015/com.app W/System.err:     at android.view.inputmethod.BaseInputConnection.setComposingText(BaseInputConnection.java:616)
02-14 12:52:30.249 24015-24015/com.app W/System.err:     at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:396)
02-14 12:52:30.249 24015-24015/com.app W/System.err:     at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage(IInputConnectionWrapper.java:85)
02-14 12:52:30.249 24015-24015/com.app W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:106)
02-14 12:52:30.249 24015-24015/com.app W/System.err:     at android.os.Looper.loop(Looper.java:164)
02-14 12:52:30.250 24015-24015/com.app W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6494)
02-14 12:52:30.250 24015-24015/com.app W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
02-14 12:52:30.250 24015-24015/com.app W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
02-14 12:52:30.250 24015-24015/com.app W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

**Comment by tatanka987** [comment]
by first message:
* it happen because you want get recipientId from dialog which didn't initiated by QBChatServise (we need chatService for determine current user then we cat  determine recipient user), for solving your issue you can:
** save id of current user in app an compare it with occupantIds (if occupant's id not equals current user's id it means this occupant is recipient);
** init qbChatDialog with logged qbChatService before call  Dialog.convert.

by second message:
* it means you not logged in to the chat before do action on chat connection (in your case send message).

**Comment by Shahjahan786** [comment]
Login to chat and after some time remaining idle my chat connection is dropped automatically and reconnected again within some delay.

 I want no connection drop while my application is running either in foreground or background

**Comment by bhaveshACME** [comment]
Chat login onError(): Attempt to invoke interface method 'boolean com.quickblox.chat.connections.ChatConnectionExtensionAble.isSupportStreamManagement()' on a null object reference

**Comment by sabininnov** [comment]
@bhaveshACME how you solve this above issuee?? I am stick with this.please respond!

**Comment by QB-nikolay-zolotarov** [comment]
Hello QuickBlox customer,

This is Nikolay from QuickBlox support.

The issue was closed as it was outdated.

Please check the relevant section of our documentation here:
[https://docs.quickblox.com/docs/android-authentication](https://docs.quickblox.com/docs/android-authentication)

Also, please update the SDK to the latest version:
[https://github.com/QuickBlox/quickblox-android-sdk-releases/releases/tag/3.9.11](https://github.com/QuickBlox/quickblox-android-sdk-releases/releases/tag/3.9.11)

Additionally, please check our new samples:
[https://docs.quickblox.com/docs/code-samples#chat-samples](https://docs.quickblox.com/docs/code-samples#chat-samples)

If it is still relevant after reviewing the updated information, feel free to open a new issue.

Have a nice day.
