### ISSUE TITLE
SASLAuthentication error 

### ISSUE THREAD

**Issue by woutergoossens** [QuickBlox/quickblox-android-sdk#57]
Hi,

I am getting this error quit often.
What is the root cause for this? 

SASL/SSL problems? 

I am trying to login to a chat with QBChatService.login but sometimes I get this error. 

Any help is appreciated.

Thanks,

Wouter
```
01-04 14:07:41.782    3316-4800/com.codebrothrs.elseapp D/QBASDK﹕ Login to chat, user JID: 1026410-9723, resource: 358240052342300
01-04 14:07:41.782    3316-4874/com.codebrothrs.elseapp W/System.err﹕ org.jivesoftware.smack.SmackException$NoResponseException
01-04 14:07:41.782    3316-4874/com.codebrothrs.elseapp W/System.err﹕ at org.jivesoftware.smack.SASLAuthentication.authenticate(SASLAuthentication.java:346)
01-04 14:07:41.792    3316-4874/com.codebrothrs.elseapp W/System.err﹕ at org.jivesoftware.smack.tcp.XMPPTCPConnection.login(XMPPTCPConnection.java:244)
01-04 14:07:41.792    3316-4874/com.codebrothrs.elseapp W/System.err﹕ at com.quickblox.chat.QBChatService.login(QBChatService.java:243)
01-04 14:07:41.792    3316-4874/com.codebrothrs.elseapp W/System.err﹕ at com.quickblox.chat.QBChatService.login(QBChatService.java:218)
01-04 14:07:41.792    3316-4874/com.codebrothrs.elseapp W/System.err﹕ at com.quickblox.q_municate_core.qb.helpers.QBChatRestHelper.login(QBChatRestHelper.java:48)
01-04 14:07:41.792    3316-4874/com.codebrothrs.elseapp W/System.err﹕ at com.quickblox.q_municate_core.qb.commands.QBLoginChatCommand.tryLogin(QBLoginChatCommand.java:60)
01-04 14:07:41.792    3316-4874/com.codebrothrs.elseapp W/System.err﹕ at com.quickblox.q_municate_core.qb.commands.QBLoginChatCommand.perform(QBLoginChatCommand.java:45)
01-04 14:07:41.792    3316-4874/com.codebrothrs.elseapp W/System.err﹕ at com.quickblox.q_municate_core.core.command.CompositeServiceCommand.perform(CompositeServiceCommand.java:29)
01-04 14:07:41.792    3316-4874/com.codebrothrs.elseapp W/System.err﹕ at com.quickblox.q_municate_core.core.command.ServiceCommand.execute(ServiceCommand.java:27)
01-04 14:07:41.792    3316-4874/com.codebrothrs.elseapp W/System.err﹕ at com.quickblox.q_municate_core.service.QBService$1.run(QBService.java:564)
01-04 14:07:41.792    3316-4874/com.codebrothrs.elseapp W/System.err﹕ at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
01-04 14:07:41.792    3316-4874/com.codebrothrs.elseapp W/System.err﹕ at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
01-04 14:07:41.792    3316-4874/com.codebrothrs.elseapp W/System.err﹕ at java.lang.Thread.run(Thread.java:841)
```

**Comment by soulfly** [comment]
SASL issue is related to wrong chat login, the first thing to do should be checking login credentials

**Comment by woutergoossens** [comment]
The login credentials are fine, that was the first thing I checked. I get this error not all the time (for the same user), sometime the login succeeds but sometime I get this error (without changing the credentials).

What should be the second thing I need to check?

**Comment by woutergoossens** [comment]
Found a similar problem - https://community.igniterealtime.org/thread/52359 

Quickblox SDK is also using aSmack-4.0.4 right?

**Comment by woutergoossens** [comment]
Any idea what the issue could be? I am using the same credentials every time but I get this error often..
My client cannot chat anymore because of this problem..

Thanks
