### ISSUE TITLE
Old Quickblox libraries Give error to getting ChatDialog detail 

### ISSUE THREAD

**Issue by zadShaikh** [QuickBlox/quickblox-android-sdk#594]
I have use this libraries:

 compile("com.quickblox:quickblox-android-sdk-messages:2.6.1@aar") {
        transitive = true
    }
compile "com.quickblox:quickblox-android-sdk-core:2.6.1@aar"

compile("com.quickblox:quickblox-android-sdk-chat:2.6.1@aar") {
        transitive=true   }

compile("com.quickblox:quickblox-android-sdk-content:2.6.1@aar") {
        transitive=true}

This is my code 

 #  _**QBChatService.getInstance().getPrivateChatManager().createDialog(opponentId, new QBEntityCallback<QBDialog>()**_ {
                    @Override
                    public void onSuccess(QBDialog privateDialog, Bundle params) {
                        Log.e("qb", "dialog created");
                  
                        ChatActivity.startForResult(ChatDialogs.this, REQUEST_MARK_READ,
                                privateDialog, userId, isPush, isFriend, name);
                        ProgressDialogFragment.hide(getSupportFragmentManager());
                        finish();
                    }

                    @Override
                    public void onError(QBResponseException responseException) {
                        Log.e("qb", "dialog failed " + responseException.getMessage());
                    }
                });

log : 

  java.lang.RuntimeException: Unable to start activity ComponentInfo{com.syncmate.android/com.Example.android.activities.ChatDialogs}: java.lang.NullPointerException: Attempt to invoke virtual method 'com.quickblox.core.QBRequestCanceler com.quickblox.chat.QBPrivateChatManager.createDialog(int, com.quickblox.core.QBEntityCallback)' on a null object reference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2490)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2550)
        at android.app.ActivityThread.access$1100(ActivityThread.java:154)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1401)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:157)
        at android.app.ActivityThread.main(ActivityThread.java:5615)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:774)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:652)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'com.quickblox.core.QBRequestCanceler com.quickblox.chat.QBPrivateChatManager.createDialog(int, com.quickblox.core.QBEntityCallback)' on a null object reference
        at com.syncmate.android.activities.ChatDialogs.onCreate(ChatDialogs.java:92)
        at android.app.Activity.performCreate(Activity.java:6362)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2443)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2550) 
        at android.app.ActivityThread.access$1100(ActivityThread.java:154) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1401) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:157) 
        at android.app.ActivityThread.main(ActivityThread.java:5615) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:774) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:652) 
05-05 17:30:58.108 469-469/? E/lowmemorykiller: Error writing /proc/23278/oom_score_adj; errno=22

**Comment by RomanPronin** [comment]
Hi @zadShaikh, you've got NullPointerException on getPrivateChatManager() cause you are not logged in chat. And we recommend using our latest version SDK.

**Comment by zadShaikh** [comment]
Hi **@RomanPronin**  can you give me old libraries **get  Group history(Message)**  Syntax and function name. and How can i get group messages from **QuickBlox**

**Comment by RomanPronin** [comment]
In v. 2.6 to get a chat history for particular dialog use:
```
QBChatService.getDialogMessages(dialog, requestBuilder, qBEntityCallback)
```
And to get only QBDialogType.GROUP type dialogs:
```
QBChatService.getChatDialogs(QBDialogType.GROUP, requestBuilder, qBEntityCallback)
```
We do not support old versions of the SDK, such as 2.6. Use our latest version SDK, at least 3.8.0.

**Comment by zadShaikh** [comment]
I am adding new libraries  compile but add this library **'com.quickblox:chat-message-adapter:2.0'**
its give **Manifest merger failed with multiple errors, see logs** But i don't have any same library in my project.

**Comment by zadShaikh** [comment]
![untitled2](https://user-images.githubusercontent.com/17671398/39765680-7ff0857a-52f3-11e8-9382-fd9d96472925.png)


This my added libraries

**Comment by QB-nikolay-zolotarov** [comment]
Hello QuickBlox customer,

This is Nikolay from QuickBlox support.

The issue was closed as it was outdated.

Please check the relevant section of our documentation here:
[https://docs.quickblox.com/docs/android-chat-dialogs](https://docs.quickblox.com/docs/android-chat-dialogs)

Also, please update the SDK to the latest version:
[https://github.com/QuickBlox/quickblox-android-sdk-releases/releases/tag/3.9.11](https://github.com/QuickBlox/quickblox-android-sdk-releases/releases/tag/3.9.11)

Additionally, please check our new samples:
[https://docs.quickblox.com/docs/code-samples#chat-samples](https://docs.quickblox.com/docs/code-samples#chat-samples)

If it is still relevant after reviewing the updated information, feel free to open a new issue.

Have a nice day.
