### ISSUE TITLE
QBRoster org.jivesoftware.smack.SmackException$NotLoggedInException: Client is not logged in

### ISSUE THREAD

**Issue by Shahjahan786** [QuickBlox/quickblox-android-sdk#597]
I'm using QBRoster whenever I add/remove entry from roster sometime it gives following exception even I'm loggedin to chat.

05-09 20:57:12.400 15226-15226/com.my.app W/System.err: org.jivesoftware.smack.SmackException$NotLoggedInException: Client is not logged in
        at org.jivesoftware.smack.roster.Roster.createEntry(Unknown Source)
        at com.quickblox.chat.QBRoster.createEntry(Unknown Source)
05-09 20:57:12.401 15226-15226/com.myapp W/System.err:     at com.my.app.chat.utils.ChatHelper.sendFriendRequest(ChatHelper.java:1451)
        at com.my.app.chat.ui.adapter.AddContactThroughDeviceAdapter$ActionButtonClickListener.onClick(AddContactThroughDeviceAdapter.java:390)
        at android.view.View.performClick(View.java:6199)
        at android.view.View$PerformClick.run(View.java:23235)
        at android.os.Handler.handleCallback(Handler.java:836)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:203)
05-09 20:57:12.402 15226-15226/com.my.app W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6251)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1073)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:934)

**Comment by Shahjahan786** [comment]
Any update on this?

**Comment by RomanPronin** [comment]
I suppose you are not indeed logged in the chat at the time of using the roster. Enable XML logs  QBChatService.setDebugEnabled(true); and attach logs with log in chat and using roster.

**Comment by Shahjahan786** [comment]
Kindly find bellow log

https://gist.github.com/Shahjahan786/fc71ea350d90a4ca48aa825dce033aa4https://gist.github.com/Shahjahan786/fc71ea350d90a4ca48aa825dce033aa4

**Comment by RomanPronin** [comment]
Your roster instance is not valid, cause of logout. So, after second login to chat you should initialize roster again: roster = QBChatService.getInstance().getRoster()
