### ISSUE TITLE
can't join group chat 

### ISSUE THREAD

**Issue by justin86** [QuickBlox/quickblox-android-sdk#624]
I got this error when i try to create group chat dialog  and join .
Right now this sample sdk  not working the create group chat dialog and join.

W/System.err: com.quickblox.core.exception.QBResponseException: XMPPError: internal-server-error - wait
        at com.quickblox.chat.QBAbstractChat$2.run(Unknown Source)
        at android.os.Handler.handleCallback(Handler.java:754)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:163)
        at android.app.ActivityThread.main(ActivityThread.java:6228)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)

**Comment by nablai** [comment]
Same here

**Comment by QB-nikolay-zolotarov** [comment]
Hello QuickBlox customer,

This is Nikolay from QuickBlox support.

The issue was closed as it was outdated.

Please check the relevant section of our documentation here:
[https://docs.quickblox.com/docs/android-chat-dialogs#join-dialog](https://docs.quickblox.com/docs/android-chat-dialogs#join-dialog)

Also, please update the SDK to the latest version:
[https://github.com/QuickBlox/quickblox-android-sdk-releases/releases/tag/3.9.11](https://github.com/QuickBlox/quickblox-android-sdk-releases/releases/tag/3.9.11)

Additionally, please check our new samples:
[https://docs.quickblox.com/docs/code-samples#chat-samples](https://docs.quickblox.com/docs/code-samples#chat-samples)

If it is still relevant after reviewing the updated information, feel free to open a new issue.

Have a nice day.
