### ISSUE TITLE
Adding Firebase Auth causing error 

### ISSUE THREAD

**Issue by DemindoO** [QuickBlox/quickblox-android-sdk#638]
I have to authenticate the phone number .For this purpose I am adding fire base dependencies 

    implementation 'com.google.firebase:firebase-auth:16.0.5'
    implementation 'com.google.firebase:firebase-core:16.0.4'
 
After this application get crash and crash is 

2018-10-17 12:18:19.982 20511-20511/com.inisde.universitychat E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.inisde.universitychat, PID: 20511
    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/common/util/zzq;
        at com.google.android.gms.gcm.GcmTaskService.onBind(Unknown Source:2)
        at android.app.ActivityThread.handleBindService(ActivityThread.java:3559)
        at android.app.ActivityThread.access$1400(ActivityThread.java:199)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1671)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.common.util.zzq" on path: DexPathList[[zip file "/data/app/com.inisde.universitychat-SKU-fIFmrcWtIqiWHCTezg==/base.apk"],nativeLibraryDirectories=[/data/app/com.inisde.universitychat-SKU-fIFmrcWtIqiWHCTezg==/lib/x86, /data/app/com.inisde.universitychat-SKU-fIFmrcWtIqiWHCTezg==/base.apk!/lib/x86, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.google.android.gms.gcm.GcmTaskService.onBind(Unknown Source:2) 
        at android.app.ActivityThread.handleBindService(ActivityThread.java:3559) 
        at android.app.ActivityThread.access$1400(ActivityThread.java:199) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1671) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6669) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 

Is any solution? what i am doing wrong

**Comment by imran-samed** [comment]
@DemindoO You found any solution, i'm also facing same issue

**Comment by g-balas** [comment]
same here

**Comment by RazibKani** [comment]
you found any solution for this?

**Comment by DemindoO** [comment]
no

**Comment by RazibKani** [comment]
I'm solved this crash by adding 'com.google.android.gms:play-services-gcm' dependency even you don't use it..
Like it needed by Quickblox SDK,

`implementation "com.google.firebase:firebase-core:$rootProject.firebaseCoreVersion"
implementation "com.google.firebase:firebase-messaging:$rootProject.firebaseMessagingVersion"
implementation "com.google.android.gms:play-services-gcm:$rootProject.gmsGcmVersion"`
