### ISSUE TITLE
Audio call not getting

### ISSUE THREAD

**Issue by Vikita080** [QuickBlox/quickblox-android-sdk#647]
Hello support team,

I'm not getting an incoming call, when start call to the opponent user he not getting calls, but current user be able to do outgoing calls,

and when I call to the opponent user getting below log:
:=>11-01 19:05:23.761 22043-23720/com.app.eljebo W/org.webrtc.Logging: **NetworkMonitorAutoDetect: Unable to obtain permission to request a cellular network.**

but yes, outgoing is working and then I disconnect outgoing call getting Activity leaked, see below lines:

CallActivity has leaked ServiceConnection android.bluetooth.BluetoothHeadset$2@4730ed0 that was originally bound here
    android.app.ServiceConnectionLeaked: Activity com.app.eljebo.activity.Home.**CallActivity has leaked ServiceConnection android.bluetooth.BluetoothHeadset$2@4730ed0 that was originally bound here**
        at android.app.LoadedApk$ServiceDispatcher.<init>(LoadedApk.java:1124)
        at android.app.LoadedApk.getServiceDispatcher(LoadedApk.java:1018)
        at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1331)
        at android.app.ContextImpl.bindServiceAsUser(ContextImpl.java:1321)
        at android.content.ContextWrapper.bindServiceAsUser(ContextWrapper.java:611)
        at android.bluetooth.BluetoothHeadset.doBind(BluetoothHeadset.java:305)
        at android.bluetooth.BluetoothHeadset.<init>(BluetoothHeadset.java:298)
        at android.bluetooth.BluetoothAdapter.getProfileProxy(BluetoothAdapter.java:1947)
        at com.quickblox.videochat.webrtc.AppRTCBluetoothManager.getBluetoothProfileProxy(AppRTCBluetoothManager.java:419)
        at com.quickblox.videochat.webrtc.AppRTCBluetoothManager.start(AppRTCBluetoothManager.java:264)
        at com.quickblox.videochat.webrtc.AppRTCAudioManager.start(AppRTCAudioManager.java:277)
        at com.app.eljebo.activity.Home.CallActivity.startAudioManager(CallActivity.java:223)
        at com.app.eljebo.activity.Home.CallActivity.onCreate(CallActivity.java:134)

So, what should I do? 
Please help me, I'm spending more than 2 days, but still not solve the issue.

I'm using below dependency version:=>
    implementation 'com.quickblox:quickblox-android-sdk-core:3.8.1@aar'
    implementation 'com.quickblox:quickblox-android-sdk-chat:3.8.1'
    implementation 'com.quickblox:quickblox-android-sdk-messages:3.8.1'
    implementation 'com.quickblox:quickblox-android-sdk-videochat-webrtc:3.8.1'

Thanks.

**Comment by QB-nikolay-zolotarov** [comment]
Hello QuickBlox customer,

This is Nikolay from QuickBlox support.

The issue was closed as it was outdated.

Please check the relevant section of our documentation here:
[https://docs.quickblox.com/docs/android-video-calling](https://docs.quickblox.com/docs/android-video-calling)

Also, please update the SDK to the latest version:
[https://github.com/QuickBlox/quickblox-android-sdk-releases/releases/tag/3.9.11](https://github.com/QuickBlox/quickblox-android-sdk-releases/releases/tag/3.9.11)

Additionally, please check our new samples:
[https://docs.quickblox.com/docs/code-samples#video-calling-samples](https://docs.quickblox.com/docs/code-samples#video-calling-samples)

If it is still relevant after reviewing the updated information, feel free to open a new issue.

Have a nice day.
