### ISSUE TITLE
Get crash in ResourceUtils

### ISSUE THREAD

**Issue by alirezaeiii** [QuickBlox/quickblox-android-sdk#703]
I receive following crash log in kotlin-sample-chat when I start the app :
  --------- beginning of crash
2020-04-09 12:56:11.442 29619-29619/com.quickblox.sample.chat.kotlin E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.quickblox.sample.chat.kotlin, PID: 29619
    android.content.res.Resources$NotFoundException: Resource ID #0x0
        at android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:228)
        at android.content.res.Resources.getColor(Resources.java:976)
        at android.content.res.Resources.getColor(Resources.java:952)
        at com.quickblox.sample.chat.kotlin.utils.ResourceUtilsKt.getCircleColor(ResourceUtils.kt:35)
        at com.quickblox.sample.chat.kotlin.utils.ResourceUtilsKt.getColorCircleDrawable(ResourceUtils.kt:28)
        at com.quickblox.sample.chat.kotlin.ui.adapter.DialogsAdapter.getView(DialogsAdapter.kt:60)
        at android.widget.AbsListView.obtainView(AbsListView.java:3219)
        at android.widget.ListView.makeAndAddView(ListView.java:2219)
        at android.widget.ListView.fillDown(ListView.java:827)
        at android.widget.ListView.fillFromTop(ListView.java:888)
        at android.widget.ListView.layoutChildren(ListView.java:1930)
        at android.widget.AbsListView.onLayout(AbsListView.java:2991)
        at android.view.View.layout(View.java:22419)
        at android.view.ViewGroup.layout(ViewGroup.java:6584)
        at com.orangegangsters.github.swipyrefreshlayout.library.SwipyRefreshLayout.onLayout(SwipyRefreshLayout.java:583)
        at android.view.View.layout(View.java:22419)
        at android.view.ViewGroup.layout(ViewGroup.java:6584)
        at androidx.coordinatorlayout.widget.CoordinatorLayout.layoutChild(CoordinatorLayout.java:1183)
        at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayoutChild(CoordinatorLayout.java:870)
        at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:889)
        at android.view.View.layout(View.java:22419)
        at android.view.ViewGroup.layout(ViewGroup.java:6584)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:22419)
        at android.view.ViewGroup.layout(ViewGroup.java:6584)
        at androidx.appcompat.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:446)
        at android.view.View.layout(View.java:22419)
        at android.view.ViewGroup.layout(ViewGroup.java:6584)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:22419)
        at android.view.ViewGroup.layout(ViewGroup.java:6584)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
        at android.view.View.layout(View.java:22419)
        at android.view.ViewGroup.layout(ViewGroup.java:6584)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at com.android.internal.policy.DecorView.onLayout(DecorView.java:1041)
        at android.view.View.layout(View.java:22419)
        at android.view.ViewGroup.layout(ViewGroup.java:6584)
        at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3378)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2842)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1888)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8511)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
        at android.view.Choreographer.doCallbacks(Choreographer.java:761)
        at android.view.Choreographer.doFrame(Choreographer.java:696)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7050)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)

**Comment by alexparvus1** [comment]
It seems that class ResourceUtils.kt can't find the color.
Please try to replace the logic in getCircleColor(...) with your own logic of colors choosing.

**Comment by QB-nikolay-zolotarov** [comment]
@alirezaeiii Hello

This is Nikolay from QuickBlox support.

Please let me know if you had a chance to check the previous reply and try the provided solution.

If there is no reply within 5 business days, the issue will be closed as outdated.
