### ISSUE TITLE
 Didn't find class "org.webrtc.VideoRenderer$I420Frame" during start audio/video call

### ISSUE THREAD

**Issue by gurinovich89** [QuickBlox/quickblox-android-sdk#707]
Application had used QuickBlox 3.3.0 and audio/video calling had worked fine. 
After it I migrated project to AndroidX and updated QuickBlox to 3.9.2. 
```
implementation 'com.quickblox:quickblox-android-sdk-videochat-webrtc:3.9.2'
implementation 'com.quickblox:quickblox-android-sdk-core:3.9.2'
implementation 'com.quickblox:quickblox-android-sdk-messages:3.9.2'
implementation 'com.quickblox:quickblox-android-sdk-chat:3.9.2'
implementation 'com.quickblox:quickblox-android-sdk-content:3.9.2'
implementation 'com.quickblox:quickblox-android-sdk-conference:3.9.2'
implementation 'com.quickblox:quickblox-android-sdk-customobjects:3.9.2'
implementation 'com.quickblox:chat-message-adapter:2.0' 
``` 

and Audio/Video calling doesn't work and get crash

```java.lang.ClassNotFoundException: Didn't find class "org.webrtc.VideoRenderer$I420Frame" on path: DexPathList[[zip file "/data/app/<app name.......>-_VAGnG6v3f4FSMKLE-7YiA==/base.apk"],nativeLibraryDirectories=[/data/app/<app name.......>-_VAGnG6v3f4FSMKLE-7YiA==/lib/x86, /data/app/<app name.......>-_VAGnG6v3f4FSMKLE-7YiA==/base.apk!/lib/x86, /system/lib, /system/product/lib]]
 W/System.err:     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
 W/System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
 W/System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
 W/System.err:     at java.lang.Runtime.nativeLoad(Native Method)
 W/System.err:     at java.lang.Runtime.nativeLoad(Runtime.java:1115)
 W/System.err:     at java.lang.Runtime.loadLibrary0(Runtime.java:1069)
 W/System.err:     at java.lang.Runtime.loadLibrary0(Runtime.java:1007)
 W/System.err:     at java.lang.System.loadLibrary(System.java:1667)
 W/System.err:     at org.webrtc.NativeLibrary$DefaultLoader.load(NativeLibrary.java:21)
 W/System.err:     at org.webrtc.NativeLibrary.initialize(NativeLibrary.java:44)
 W/System.err:     at org.webrtc.PeerConnectionFactory.initialize(PeerConnectionFactory.java:216)
 W/System.err:     at com.quickblox.videochat.webrtc.PeerFactoryManager.initPeerConnectionFactory(PeerFactoryManager.java:149)
 W/System.err:     at com.quickblox.videochat.webrtc.PeerFactoryManager.access$100(PeerFactoryManager.java:25)
 W/System.err:     at com.quickblox.videochat.webrtc.PeerFactoryManager$1.run(PeerFactoryManager.java:100)
 W/System.err:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
 W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
 W/System.err:     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
 W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
 W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
 W/System.err:     at java.lang.Thread.run(Thread.java:919)
 E/rtc: #
    # Fatal error in ../../webrtc/api/android/jni/classreferenceholder.cc, line 119
    # last system error: 88
    # Check failed: !jni->ExceptionCheck()
    # error during FindClass: org/webrtc/VideoRenderer$I420Frame
```

**Environment details**
```
android {
    compileSdkVersion 28
    buildToolsVersion '28.0.3'
    defaultConfig {
         minSdkVersion 21
        targetSdkVersion 28
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        multiDexEnabled true
    }
```
Android Gradle Plugin Version 3.2.0
Gradle version 5.6.4
```
buildTypes {
        debug {
            minifyEnabled false
            shrinkResources false
            proguardFile 'proguard-rules.pro'
            zipAlignEnabled false
        }

        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
```

In gradle.properties
```kotlin.code.style=official
org.gradle.parallel=false
org.gradle.configureondemand=true
android.useAndroidX=true
android.enableJetifier=true
```

And as you see I cannot use shrinking and therefore proguard rules like as 
```
-keep class org.webrtc.VideoRenderer$I420Frame { *; }
```
 cannot help me. 

For starting call I use code like this 
```
QBRTCTypes.QBConferenceType conferenceType = QBRTCTypes.QBConferenceType.QB_CONFERENCE_TYPE_VIDEO;

        QBRTCClient qbrtcClient = QBRTCClient.getInstance(getApplicationContext());
        QBRTCSession newQbRtcSession = null;
        try {
            newQbRtcSession = qbrtcClient.createNewSessionWithOpponents(occupantIds, conferenceType);
        } catch (IllegalStateException e) {
            e.printStackTrace();
        }
        if (newQbRtcSession != null) {
            //Adding custom parameters for voice and video call
            HashMap<String, String> userInfo = new HashMap<>();
            userInfo.put("dataTag", tagType);
            userInfo.put("qbDialogId", qbChatDialog.getDialogId());
            if (isVideoCall)
                userInfo.put("CallType", "Video");
            else
                userInfo.put("CallType", "Audio");
            newQbRtcSession.startCall(userInfo);
            WebRtcSessionManager.getInstance(this).setCurrentSession(newQbRtcSession);
            CallActivity.start(this, false);
        }
```
Maybe somebody can help me?

**Comment by alexparvus1** [comment]
Thanks for your exhaustive question! 

Which build-type did you use when you get an application crash? (debug/release)

It might be you still need to check your proguard-rules file. 
You can find it in one of our sample: https://github.com/QuickBlox/quickblox-android-sdk/blob/master/sample-videochat-java/proguard-rules.pro
And then maybe you need to add the rule like: 
`-keep class org.webrtc.** { *; }`

In addition, as I found in your project - your Gradle Plugin Version(**3.2.0**) requires the Gradle Version **4.6**. You can find this information in https://developer.android.com/studio/releases/gradle-plugin#updating-gradle

**Comment by gurinovich89** [comment]
Thanks, for your answer. It was my trouble. I didn't notice that old version of quickBlox(3.2.0) was  using native *.so libs which has already located in project(app/src/main/jniLibs). Beginning with QuickBlox 3.7.0 we can don't use native *.so webrtc libs directly in our App code. After removing all old jniLibs audio/video calling started to work perfectly.
![image](https://user-images.githubusercontent.com/5954707/82659138-db4f6c00-9c30-11ea-9f90-f23235ca2696.png)

Therefore my problem is resolved by removing all native webrtc jniLibs in project.
