### ISSUE TITLE
I have issue when i'm enable proguard 

### ISSUE THREAD

**Issue by Ahmedbadereldin** [QuickBlox/quickblox-android-sdk#733]
D/QBASDK: org.json.JSONException: JSONObject["last_message_user_id"] not a string.
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.qiotic.yayacar, PID: 30147
    java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
        at com.quickblox.chat.model.QBChatDialog.getType(Unknown Source:2)
        at com.quickblox.chat.model.QBChatDialog.isPrivate(Unknown Source:2)
        at com.quickblox.chat.model.QBChatDialog.initChat(Unknown Source:0)
        at com.quickblox.chat.model.QBChatDialog.initChatFromRest(Unknown Source:6)
        at com.quickblox.chat.model.QBDialogDeserializer.deserialize(Unknown Source:386)
        at com.quickblox.chat.model.QBDialogDeserializer.deserialize(Unknown Source:0)
        at com.google.gson.internal.bind.TreeTypeAdapter.b(SourceFile:69)
        at c.l.c.w.m.c.b(SourceFile:41)
        at com.google.gson.internal.bind.CollectionTypeAdapterFactory$a.e(SourceFile:82)
        at com.google.gson.internal.bind.CollectionTypeAdapterFactory$a.b(SourceFile:61)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$a.a(SourceFile:131)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$b.b(SourceFile:222)
        at c.l.c.f.g(SourceFile:932)
        at c.l.c.f.h(SourceFile:897)
        at c.l.c.f.j(SourceFile:846)
        at com.quickblox.core.parser.QBJsonParser.parseJsonResponse(Unknown Source:46)
        at com.quickblox.core.parser.QBLimitedJsonParser.parseJsonResponse(Unknown Source:0)
        at com.quickblox.core.parser.QBJsonParser.parse(Unknown Source:30)
        at c.v.a.c.m$c.completedWithResponse(Unknown Source:18)
        at c.v.a.c.m.completedWithResponse(Unknown Source:11)
        at com.quickblox.core.server.HttpRequestRunnable$1.handleMessage(Unknown Source:48)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:224)
        at android.app.ActivityThread.main(ActivityThread.java:7560)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

**Comment by alexparvus1** [comment]
Please check the Proguard section there - https://github.com/QuickBlox/quickblox-android-sdk/blob/master/README.md#customize-proguard-in-android-studio
