### ISSUE TITLE
Android Studio - UNEXPECTED TOP-LEVEL EXCEPTION QuickBlox chat jar

### ISSUE THREAD

**Issue by shivamsingh** [QuickBlox/quickblox-android-sdk#76]
http://stackoverflow.com/questions/29517605/android-studio-unexpected-top-level-exception-quickblox-chat-jar

com.android.dx.util.DexException: Multiple dex files define Landroid/support/androidannotations;
    at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:592)
    at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:550)
    at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:531)
    at com.android.dx.merge.DexMerger.mergeDexBuffers(DexMerger.java:168)
    at com.android.dx.merge.DexMerger.merge(DexMerger.java:186)
    at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:300)
    at com.android.dx.command.dexer.Main.run(Main.java:232)
    at com.android.dx.command.dexer.Main.main(Main.java:174)
    at com.android.dx.command.Main.main(Main.java:91)

Gradle dependecy:

compile 'jars/quickblox-android-sdk-chat-2.2.1.jar'
Note: I also use android-support-v4 dependecy.

From my understanding error seems like android.support.annotations exists in
both 'quickblox chat' & 'android support'.

So is there any way I can exclude 'android.support.annotations' package from quickblox-android-sdk-chat-2.2.1.jar.

**Comment by soulfly** [comment]
This was fixed in a latest commit today https://github.com/QuickBlox/quickblox-android-sdk/commit/d326b402a6bbb8517434489873c4d2a8b2688e51

**Comment by shivamsingh** [comment]
link is broken, can you share updated link.
https://github.com/QuickBlox/quickblox-android-sdk/tree/master/jars

**Comment by soulfly** [comment]
Just download latest version from master

**Comment by shivamsingh** [comment]
Can u please share the link for same.
I can't see any update in this repository, also there is no jars folder in repo.

**Comment by shivamsingh** [comment]
Hey soulfly,

Thanks for your quick revert. But I am not able to get updated jar from master.
There is no jars folder in master repository.

I would appreciate if you can share updated jar download link.

**Comment by soulfly** [comment]
Here it is, please check again

https://github.com/QuickBlox/quickblox-android-sdk/tree/master/jars

WebRTC sample works well now

**Comment by shivamsingh** [comment]
Thanks a ton
