### ISSUE TITLE
Not receiving call sessions and push notifications properly

### ISSUE THREAD

**Issue by Ahmadpashaquarterpi** [QuickBlox/quickblox-android-sdk#773]
**QuickBlox SDK Version:** 3.9.11

**PushNotification Type in Manifest:** GCM 

**Did this work before?**
Yes, till ( 17 November 2021 ).

**Expected behavior**
Notifications and call sessions should be received properly in time.

**Actual behavior**
Notifications are not working properly on **android 7,8**.
(Notifications are working as expected on android 9,10).
And call sessions are not receiving consistently.
At one moment, it starts working and the other moment it stops working and user does not receive call session even when user is online.

**Steps to reproduce the behavior**
this situation is appearing on android 7 and 8.

When the Type in Manifest is FCM, it is causing application to crash with error **Didn't find class "com.google.firebase.iid.FirebaseInstanceId"** )

**Comment by QB-liubov-shmatok** [comment]
Hello Ahmad, 

This is Liubov from QuickBlox support. 

In order to investigate the issue, we would like to ask you to test the flow on our samples. Please follow these links 
- https://docs.quickblox.com/docs/code-samples#chat-samples ;
- https://docs.quickblox.com/docs/code-samples#video-calling-samples 

In case the error mentioned still reproduces, please get back to us with steps to reproduce the error and full REST + XMPP + WebRTC logs.

**Comment by Ahmadpashaquarterpi** [comment]
ok, I get back here after trying the samples.

**Comment by Ahmadpashaquarterpi** [comment]
Thanks Liubov,

The issue has been resolved.

it was a mistake on the developers end.

**Comment by sagarehs** [comment]
@QB-liubov-shmatok please check this Crashlog

Firebase library update "com.google.firebase:firebase-bom:26.8.0" to "com.google.firebase:firebase-bom:29.0.0"

qbSdkVersion = '3.9.2'

Caused by java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/firebase/iid/FirebaseInstanceId;
       at com.quickblox.messages.services.a.a.<init>(:3)
       at com.quickblox.messages.services.a.b.a(:2)
       at com.quickblox.messages.services.SubscribeService.a(:15)
       at com.quickblox.messages.services.SubscribeService.a(:1)
       at com.quickblox.messages.services.SubscribeService.e(:12)
       at com.quickblox.messages.services.SubscribeService.b(:18)
       at com.quickblox.messages.services.SubscribeService.onHandleWork(:50)
       at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:396)
       at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:387)
       at android.os.AsyncTask$3.call(AsyncTask.java:394)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:923)

**Comment by QB-nikolay-zolotarov** [comment]
@sagarehs Let's continue the conversation here https://github.com/QuickBlox/quickblox-android-sdk/issues/781
