### ISSUE TITLE
can't able to delete messages in private dialog

### ISSUE THREAD

**Issue by vikashrathore081** [QuickBlox/quickblox-android-sdk#780]
I am using QuickBlox android sdk and when I trying to delete message its give me this exception

com.quickblox.core.exception.QBResponseException: Entity you are looking for was not found.,The resource wasn't found

Earlier its worked fine

**Comment by QB-nikolay-zolotarov** [comment]
@vikashrathore081 Hello, 

This is Nikolay from QuickBlox support.

Please make sure that you delete the message correctly according to our documentation:
https://docs.quickblox.com/docs/android-chat-messaging#delete-message

To investigate the issue further, I need the following points:
1. What SDK version are you using?
Please make sure that you use the latest version of the Android SDK:
https://github.com/QuickBlox/quickblox-android-sdk-releases/releases/tag/3.9.15
2. Is this issue intermittent or permanent?
3. What are the steps to reproduce on our side?
4. Please provide us with full REST + XMPP logs as an attachment in .txt format. There should be QB SDKs logs from application start till request and "wrong" response (error).
You can find out how to gather logs here: https://docs.quickblox.com/docs/android-setup#enable-logging
5. Versions of Android platform where reproduces the issue (e.g. Android 11).
6. Phone models (e.g. Samsung Galaxy S9).

**Comment by vikashrathore081** [comment]
1- I am using android sdk version 3.9.13
2- So time it works sometime not
3- I am Following [this doc](https://docs.quickblox.com/docs/android-chat-messaging#delete-message)
4- logs
 INLINE
        DELETE https://api.quickblox.com/chat/Message/620cee558a76c2129a23fbb5.json?force=1
2022-02-16 19:12:19.158 7370-7370/com.meenapp D/QBASDK: *********************************************************
    *** RESPONSE *** 60cc8f50-45e6-4de1-93e1-3660c163720d ***
    STATUS : 404 
    HEADERS
        Server=nginx
        Access-Control-Allow-Origin=*
        X-Request-Id=a15d6e77-6577-4627-84f4-b6575e327343
        X-Content-Type-Options=nosniff
        X-Runtime=0.020769
        Connection=close
        X-Download-Options=noopen
        X-Permitted-Cross-Domain-Policies=none
        X-Android-Received-Millis=1645018939151
        Date=Wed, 16 Feb 2022 13:42:18 GMT
        QuickBlox-REST-API-Version=0.1.1
        Referrer-Policy=strict-origin-when-cross-origin
        X-Frame-Options=SAMEORIGIN
        X-Android-Selected-Protocol=http/1.1
        Strict-Transport-Security=max-age=31536000; includeSubDomains
        Cache-Control=no-cache
        X-Android-Response-Source=NETWORK 404
        X-Android-Sent-Millis=1645018938819
        Content-Length=40
        X-XSS-Protection=1; mode=block
        QB-Token-ExpirationDate=2022-02-16 15:42:18 UTC
        Content-Type=application/json; charset=utf-8
    BODY
        '{"errors":["The resource wasn't found"]}'
2022-02-16 19:12:19.177 7370-7370/com.meenapp W/System.err: com.quickblox.core.exception.QBResponseException: Entity you are looking for was not found.,The resource wasn't found
2022-02-16 19:12:19.177 7370-7370/com.meenapp W/System.err:     at com.quickblox.core.parser.QBJsonParser.parse(Unknown Source:49)
2022-02-16 19:12:19.177 7370-7370/com.meenapp W/System.err:     at com.quickblox.auth.session.Query$VersionEntityCallback.completedWithResponse(Unknown Source:24)
2022-02-16 19:12:19.177 7370-7370/com.meenapp W/System.err:     at com.quickblox.auth.session.Query.completedWithResponse(Unknown Source:11)
2022-02-16 19:12:19.178 7370-7370/com.meenapp W/System.err:     at com.quickblox.core.server.HttpRequestRunnable$1.handleMessage(Unknown Source:46)
2022-02-16 19:12:19.178 7370-7370/com.meenapp W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:106)
2022-02-16 19:12:19.178 7370-7370/com.meenapp W/System.err:     at android.os.Looper.loop(Looper.java:236)
2022-02-16 19:12:19.178 7370-7370/com.meenapp W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:8061)
2022-02-16 19:12:19.178 7370-7370/com.meenapp W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2022-02-16 19:12:19.178 7370-7370/com.meenapp W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
2022-02-16 19:12:19.178 7370-7370/com.meenapp W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
5- I am testing it on android 11
6- Phone model MI 9T Pro

**Comment by vikashrathore081** [comment]
Any update??
@QB-nikolay-zolotarov

**Comment by QB-nikolay-zolotarov** [comment]
@vikashrathore081 Please double-check if the message you are trying to delete exist.

Also, please make sure that the user that tries to delete the message is added to occupants of the dialog.

Additionally, please note that only the owner can delete messages with force=1. Please make sure that the user is the owner.
