### ISSUE TITLE
Not Working push notifications with Latest Firebase bom 

### ISSUE THREAD

**Issue by sagarehs** [QuickBlox/quickblox-android-sdk#781]
*QuickBlox SDK Version:* 3.9.2

*PushNotification Type in Manifest:* FCM

*Actual behavior*
Application crashed.

Firebase library update in my Project "com.google.firebase:firebase-bom:26.8.0" to "com.google.firebase:firebase-bom:29.0.0"

Application Working fine with "com.google.firebase:firebase-bom:26.8.0"

Caused by java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/firebase/iid/FirebaseInstanceId;
at com.quickblox.messages.services.a.a.(:3)
at com.quickblox.messages.services.a.b.a(:2)
at com.quickblox.messages.services.SubscribeService.a(:15)
at com.quickblox.messages.services.SubscribeService.a(:1)
at com.quickblox.messages.services.SubscribeService.e(:12)
at com.quickblox.messages.services.SubscribeService.b(:18)
at com.quickblox.messages.services.SubscribeService.onHandleWork(:50)
at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:396)
at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:387)
at android.os.AsyncTask$3.call(AsyncTask.java:394)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at java.lang.Thread.run(Thread.java:923)

**Comment by teamaligness** [comment]
it's still happen in latest version
could you fix it?

Thank you

**Comment by vdovbnya-qb** [comment]
HI @teamaligness ,

You can try to solve this issue by adding the `firebase-iid` dependency:
`implementation 'com.google.firebase:firebase-iid'`
