### ISSUE TITLE
Push Notification not working for call

### ISSUE THREAD

**Issue by AqeelAaqi** [QuickBlox/quickblox-android-sdk#817]
i have posted my logs here when i add this metadata into Menifiest then my app crashes if i enter direct sender id then show me toast message that your metadata are not subscribe bla bla... please help me
<meta-data
            android:name="com.quickblox.messages.SENDER_ID"
            android:value="@string/sender_id" />
            
sdk
    implementation "com.quickblox:quickblox-android-sdk-messages:4.1.1"
    implementation "com.quickblox:quickblox-android-sdk-chat:4.1.1"
    implementation "com.quickblox:quickblox-android-sdk-content:4.1.1"
    implementation "com.quickblox:quickblox-android-sdk-videochat-webrtc:3.10.1"
    implementation "com.quickblox:quickblox-android-sdk-conference:3.10.1"
    implementation "com.quickblox:quickblox-android-sdk-customobjects:3.10.1"
 implementation(platform("com.google.firebase:firebase-bom:32.2.0"))
 
logs

java.lang.RuntimeException: An error occurred while executing doInBackground()
                                                                                                    	at android.os.AsyncTask$3.done(AsyncTask.java:354)
                                                                                                    	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
                                                                                                    	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
                                                                                                    	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
                                                                                                    	at java.lang.Thread.run(Thread.java:764)
                                                                                                    Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/firebase/iid/FirebaseInstanceId;
                                                                                                    	at com.quickblox.messages.services.a.a.<init>(Unknown Source:3)
                                                                                                    	at com.quickblox.messages.services.a.b.a(Unknown Source:2)
                                                                                                    	at com.quickblox.messages.services.SubscribeService.a(Unknown Source:15)
                                                                                                    	at com.quickblox.messages.services.SubscribeService.a(Unknown Source:1)
                                                                                                    	at com.quickblox.messages.services.SubscribeService.d(Unknown Source:12)
                                                                                                    	at com.quickblox.messages.services.SubscribeService.b(Unknown Source:18)
                                                                                                    	at com.quickblox.messages.services.SubscribeService.onHandleWork(Unknown Source:50)
                                                                                                    	at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:396)
                                                                                                    	at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:387)
                                                                                                    	at android.os.AsyncTask$2.call(AsyncTask.java:333)
                                                                                                    	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
                                                                                                    	at java.lang.Thread.run(Thread.java:764) 
                                                                                                    Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.iid.FirebaseInstanceId" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.app.firebasechat-BvApnXpMJ103QA80dSiZ1A==/base.apk"],nativeLibraryDirectories=[/data/app/com.app.firebasechat-BvApnXpMJ103QA80dSiZ1A==/lib/arm64, /data/app/com.app.firebasechat-BvApnXpMJ103QA80dSiZ1A==/base.apk!/lib/arm64-v8a, /system/lib64, /system/vendor/lib64]]
                                                                                                    	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
                                                                                                    	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
                                                                                                    	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                                                                    	at com.quickblox.messages.services.a.a.<init>(Unknown Source:3) 
                                                                                                    	at com.quickblox.messages.services.a.b.a(Unknown Source:2) 
                                                                                                    	at com.quickblox.messages.services.SubscribeService.a(Unknown Source:15) 
                                                                                                    	at com.quickblox.messages.services.SubscribeService.a(Unknown Source:1) 
                                                                                                    	at com.quickblox.messages.services.SubscribeService.d(Unknown Source:12) 
                                                                                                    	at com.quickblox.messages.services.SubscribeService.b(Unknown Source:18) 
                                                                                                    	at com.quickblox.messages.services.SubscribeService.onHandleWork(Unknown Source:50) 
                                                                                                    	at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:396) 
                                                                                                    	at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:387) 
                                                                                                    	at android.os.AsyncTask$2.call(AsyncTask.java:333) 
                                                                                                    	at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
                                                                                                    	at java.lang.Thread.run(Thread.java:764)

**Comment by AqeelAaqi** [comment]
resolve crashes with adding this sdk
implementation "com.google.firebase:firebase-core:21.1.1"

but still not able to receive call my subscription show message created
