### ISSUE TITLE
WebRTC sample application crash on devices without a front camera

### ISSUE THREAD

**Issue by enginegl** [QuickBlox/quickblox-android-sdk#86]
How can I handle it?

05-09 18:10:53.519  11683-11683/com.quickblox.sample.videochatwebrtcnew E/AndroidRuntime﹕ FATAL EXCEPTION: main
    java.lang.RuntimeException: Front facing camera does not exist.
            at org.webrtc.VideoCapturerAndroid.getNameOfFrontFacingDevice(VideoCapturerAndroid.java:117)
            at com.quickblox.videochat.webrtc.QBMediaStreamManager.initLocalMediaStream(QBMediaStreamManager.java:112)
            at com.quickblox.videochat.webrtc.QBRTCSession.onLocalStreamNeedAdd(QBRTCSession.java:983)
            at com.quickblox.videochat.webrtc.QBPeerChannel.setLocalMediaStream(QBPeerChannel.java:249)
            at com.quickblox.videochat.webrtc.QBPeerChannel.access$800(QBPeerChannel.java:45)
            at com.quickblox.videochat.webrtc.QBPeerChannel$4.run(QBPeerChannel.java:219)
            at android.app.Activity.runOnUiThread(Activity.java:4603)
            at com.quickblox.videochat.webrtc.QBPeerChannel.createConnection(QBPeerChannel.java:213)
            at com.quickblox.videochat.webrtc.QBPeerChannel.startAsAnswer(QBPeerChannel.java:284)
            at com.quickblox.videochat.webrtc.QBRTCSession.acceptCall(QBRTCSession.java:595)
            at com.quickblox.sample.videochatwebrtcnew.fragments.ConversationFragment.onStart(ConversationFragment.java:155)
            at android.app.Fragment.performStart(Fragment.java:1570)
            at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:863)
            at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1035)
            at android.app.BackStackRecord.run(BackStackRecord.java:635)
            at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1397)
            at android.app.FragmentManagerImpl$1.run(FragmentManager.java:426)
            at android.os.Handler.handleCallback(Handler.java:615)
            at android.os.Handler.dispatchMessage(Handler.java:92)
            at android.os.Looper.loop(Looper.java:153)
            at android.app.ActivityThread.main(ActivityThread.java:5086)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:821)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:584)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by soulfly** [comment]
This was fixed some time ago
